-- autogenerated lush spec on Sunday 14 January 2024 01:30:22 AM
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    SpecialKey                             { bg="#eeeeee", fg="#000000", }, -- SpecialKey     xxx ctermfg=16 ctermbg=255 guifg=#000000 guibg=#eeeeee
    iCursor                                { SpecialKey }, -- iCursor        xxx links to SpecialKey
    TermCursor                             { gui="reverse", }, -- TermCursor     xxx cterm=reverse gui=reverse
    NonText                                { gui="bold", fg="blue", }, -- NonText        xxx ctermfg=12 gui=bold guifg=Blue
    EndOfBuffer                            { NonText }, -- EndOfBuffer    xxx links to NonText
    Whitespace                             { NonText }, -- Whitespace     xxx links to NonText
    Directory                              { fg="cyan", }, -- Directory      xxx ctermfg=159 guifg=Cyan
    ErrorMsg                               { bg="#af0000", fg="#eeeeee", }, -- ErrorMsg       xxx ctermfg=255 ctermbg=124 guifg=#eeeeee guibg=#af0000
    NvimInvalidSpacing                     { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    IncSearch                              { gui="reverse", bg="#8a8a8a", fg="#eeeeee", }, -- IncSearch      xxx cterm=reverse ctermfg=255 ctermbg=245 gui=reverse guifg=#eeeeee guibg=#8a8a8a
    Search                                 { bg="#303030", fg="#8a8a8a", }, -- Search         xxx ctermfg=245 ctermbg=236 guifg=#8a8a8a guibg=#303030
    CurSearch                              { Search }, -- CurSearch      xxx links to Search
    QuickFixLine                           { Search }, -- QuickFixLine   xxx links to Search
    Substitute                             { Search }, -- Substitute     xxx links to Search
    MoreMsg                                { gui="bold", fg="seagreen", }, -- MoreMsg        xxx ctermfg=121 gui=bold guifg=SeaGreen
    ModeMsg                                { gui="bold", }, -- ModeMsg        xxx cterm=bold gui=bold
    LineNr                                 { fg="yellow", }, -- LineNr         xxx ctermfg=11 guifg=Yellow
    LineNrAbove                            { LineNr }, -- LineNrAbove    xxx links to LineNr
    LineNrBelow                            { LineNr }, -- LineNrBelow    xxx links to LineNr
    CursorLineNr                           { gui="bold", fg="yellow", }, -- CursorLineNr   xxx cterm=underline ctermfg=11 gui=bold guifg=Yellow
    Question                               { gui="bold", fg="green", }, -- Question       xxx ctermfg=121 gui=bold guifg=Green
    StatusLine                             { gui="bold,reverse", bg="#000000", fg="#8a8a8a", }, -- StatusLine     xxx cterm=bold,reverse ctermfg=245 ctermbg=16 gui=bold,reverse guifg=#8a8a8a guibg=#000000
    MsgSeparator                           { StatusLine }, -- MsgSeparator   xxx links to StatusLine
    StatusLineNC                           { gui="reverse", bg="#000000", fg="#303030", }, -- StatusLineNC   xxx cterm=reverse ctermfg=236 ctermbg=16 gui=reverse guifg=#303030 guibg=#000000
    Title                                  { gui="bold", fg="magenta", }, -- Title          xxx ctermfg=225 gui=bold guifg=Magenta
    FloatTitle                             { Title }, -- FloatTitle     xxx links to Title
    sym"@text.title"                       { Title }, -- @text.title    xxx links to Title
    NullLsInfoSources                      { Title }, -- NullLsInfoSources xxx links to Title
    LspInfoTitle                           { Title }, -- LspInfoTitle   xxx links to Title
    Visual                                 { gui="reverse", bg="#000000", fg="#bcbcbc", }, -- Visual         xxx cterm=reverse ctermfg=250 ctermbg=16 gui=reverse guifg=#bcbcbc guibg=#000000
    VertSplit                              { Visual }, -- VertSplit      xxx links to Visual
    VisualNOS                              { Visual }, -- VisualNOS      xxx links to Visual
    UfoPreviewCursorLine                   { Visual }, -- UfoPreviewCursorLine xxx links to Visual
    WarningMsg                             { fg="red", }, -- WarningMsg     xxx ctermfg=224 guifg=Red
    vimWarn                                { WarningMsg }, -- vimWarn        xxx links to WarningMsg
    WildMenu                               { bg="#eeeeee", fg="#585858", }, -- WildMenu       xxx ctermfg=240 ctermbg=255 guifg=#585858 guibg=#eeeeee
    Folded                                 { bg="darkgrey", fg="cyan", }, -- Folded         xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=DarkGrey
    vimFold                                { Folded }, -- vimFold        xxx links to Folded
    FoldColumn                             { bg="grey", fg="cyan", }, -- FoldColumn     xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey
    CursorLineFold                         { FoldColumn }, -- CursorLineFold xxx links to FoldColumn
    DiffAdd                                { bg="darkblue", }, -- DiffAdd        xxx ctermbg=4 guibg=DarkBlue
    DiffChange                             { bg="#eeeeee", fg="#d70000", }, -- DiffChange     xxx ctermfg=160 ctermbg=255 guifg=#d70000 guibg=#eeeeee
    diffChanged                            { DiffChange }, -- diffChanged    xxx links to DiffChange
    DiffDelete                             { gui="bold", bg="darkcyan", fg="blue", }, -- DiffDelete     xxx ctermfg=12 ctermbg=6 gui=bold guifg=Blue guibg=DarkCyan
    DiffText                               { gui="bold", bg="#ff0000", fg="#bcbcbc", }, -- DiffText       xxx cterm=bold ctermfg=250 ctermbg=196 gui=bold guifg=#bcbcbc guibg=#ff0000
    SignColumn                             { bg="#585858", fg="#af0000", }, -- SignColumn     xxx ctermfg=124 ctermbg=240 guifg=#af0000 guibg=#585858
    CursorLineSign                         { SignColumn }, -- CursorLineSign xxx links to SignColumn
    Conceal                                { bg="darkgrey", fg="lightgrey", }, -- Conceal        xxx ctermfg=7 ctermbg=242 guifg=LightGrey guibg=DarkGrey
    SpellBad                               { sp="red", bg="#870000", gui="undercurl", fg="#eeeeee", }, -- SpellBad       xxx cterm=undercurl ctermfg=255 ctermbg=88 gui=undercurl guifg=#eeeeee guibg=#870000 guisp=Red
    SpellCap                               { sp="blue", bg="#af0000", fg="#eeeeee", }, -- SpellCap       xxx ctermfg=255 ctermbg=124 guifg=#eeeeee guibg=#af0000 guisp=Blue
    SpellRare                              { sp="magenta", bg="#000000", fg="#af0000", }, -- SpellRare      xxx ctermfg=124 ctermbg=16 guifg=#af0000 guibg=#000000 guisp=Magenta
    rstEmphasis                            { SpellRare }, -- rstEmphasis    xxx links to SpellRare
    SpellLocal                             { sp="cyan", gui="undercurl", }, -- SpellLocal     xxx ctermbg=14 gui=undercurl guisp=Cyan
    Pmenu                                  { bg="#585858", fg="#eeeeee", }, -- Pmenu          xxx ctermfg=255 ctermbg=240 guifg=#eeeeee guibg=#585858
    PmenuKind                              { Pmenu }, -- PmenuKind      xxx links to Pmenu
    PmenuExtra                             { Pmenu }, -- PmenuExtra     xxx links to Pmenu
    NormalFloat                            { Pmenu }, -- NormalFloat    xxx links to Pmenu
    PmenuSel                               { bg="darkgrey", }, -- PmenuSel       xxx ctermfg=242 ctermbg=0 guibg=DarkGrey
    PmenuKindSel                           { PmenuSel }, -- PmenuKindSel   xxx links to PmenuSel
    PmenuExtraSel                          { PmenuSel }, -- PmenuExtraSel  xxx links to PmenuSel
    PmenuSbar                              { bg="grey", }, -- PmenuSbar      xxx ctermbg=248 guibg=Grey
    UfoPreviewSbar                         { PmenuSbar }, -- UfoPreviewSbar xxx links to PmenuSbar
    PmenuThumb                             { bg="#585858", fg="#080808", }, -- PmenuThumb     xxx ctermfg=232 ctermbg=240 guifg=#080808 guibg=#585858
    UfoPreviewThumb                        { PmenuThumb }, -- UfoPreviewThumb xxx links to PmenuThumb
    TabLine                                { gui="underline", bg="darkgrey", }, -- TabLine        xxx cterm=underline ctermfg=15 ctermbg=242 gui=underline guibg=DarkGrey
    TabLineSel                             { gui="bold", }, -- TabLineSel     xxx cterm=bold gui=bold
    TabLineFill                            { gui="reverse", }, -- TabLineFill    xxx cterm=reverse gui=reverse
    CursorColumn                           { bg="grey40", }, -- CursorColumn   xxx ctermbg=242 guibg=Grey40
    CursorLine                             { bg="#121212", }, -- CursorLine     xxx ctermbg=233 guibg=#121212
    ColorColumn                            { bg="darkred", }, -- ColorColumn    xxx ctermbg=1 guibg=DarkRed
    WinBar                                 { gui="bold", }, -- WinBar         xxx cterm=bold gui=bold
    WinBarNC                               { WinBar }, -- WinBarNC       xxx links to WinBar
    Cursor                                 { bg="fg", fg="bg", }, -- Cursor         xxx guifg=bg guibg=fg
    lCursor                                { bg="fg", fg="bg", }, -- lCursor        xxx guifg=bg guibg=fg
    Normal                                 { bg="#000000", fg="#bcbcbc", }, -- Normal         xxx ctermfg=250 ctermbg=16 guifg=#bcbcbc guibg=#000000
    Boolean                                { Normal }, -- Boolean        xxx links to Normal
    Exception                              { Normal }, -- Exception      xxx links to Normal
    Macro                                  { Normal }, -- Macro          xxx links to Normal
    Delimiter                              { Normal }, -- Delimiter      xxx links to Normal
    Debug                                  { Normal }, -- Debug          xxx links to Normal
    NvimSpacing                            { Normal }, -- NvimSpacing    xxx links to Normal
    DapUIVariable                          { Normal }, -- DapUIVariable  xxx links to Normal
    DapUIValue                             { Normal }, -- DapUIValue     xxx links to Normal
    vimUserFunc                            { Normal }, -- vimUserFunc    xxx links to Normal
    vimEmbedError                          { Normal }, -- vimEmbedError  xxx links to Normal
    DapUINormal                            { Normal }, -- DapUINormal    xxx links to Normal
    DapUIFrameName                         { Normal }, -- DapUIFrameName xxx links to Normal
    DapUINormalNC                          { Normal }, -- DapUINormalNC  xxx links to Normal
    FloatShadow                            { blend=80, bg="black", }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough                     { blend=100, bg="black", }, -- FloatShadowThrough xxx guibg=Black blend=100
    RedrawDebugNormal                      { gui="reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    RedrawDebugClear                       { bg="yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed                    { bg="green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugRecompose                   { bg="red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Error                                  { bg="#870000", fg="#eeeeee", }, -- Error          xxx ctermfg=255 ctermbg=88 guifg=#eeeeee guibg=#870000
    NvimInvalid                            { Error }, -- NvimInvalid    xxx links to Error
    vimOperError                           { Error }, -- vimOperError   xxx links to Error
    vimUserAttrbError                      { Error }, -- vimUserAttrbError xxx links to Error
    vimUserCmdError                        { Error }, -- vimUserCmdError xxx links to Error
    vimElseIfErr                           { Error }, -- vimElseIfErr   xxx links to Error
    vimSynError                            { Error }, -- vimSynError    xxx links to Error
    vimSyncError                           { Error }, -- vimSyncError   xxx links to Error
    luaParenError                          { Error }, -- luaParenError  xxx links to Error
    luaError                               { Error }, -- luaError       xxx links to Error
    vimError                               { Error }, -- vimError       xxx links to Error
    Todo                                   { bg="yellow", fg="blue", }, -- Todo           xxx ctermfg=0 ctermbg=11 guifg=Blue guibg=Yellow
    sym"@text.todo"                        { Todo }, -- @text.todo     xxx links to Todo
    vimTodo                                { Todo }, -- vimTodo        xxx links to Todo
    luaTodo                                { Todo }, -- luaTodo        xxx links to Todo
    String                                 { bg="#000000", fg="#8a8a8a", }, -- String         xxx ctermfg=245 ctermbg=16 guifg=#8a8a8a guibg=#000000
    SpecialComment                         { String }, -- SpecialComment xxx links to String
    sym"@string"                           { String }, -- @string        xxx links to String
    NvimString                             { String }, -- NvimString     xxx links to String
    vimString                              { String }, -- vimString      xxx links to String
    luaString2                             { String }, -- luaString2     xxx links to String
    luaString                              { String }, -- luaString      xxx links to String
    Constant                               { bg="#000000", fg="#d0d0d0", }, -- Constant       xxx ctermfg=252 ctermbg=16 guifg=#d0d0d0 guibg=#000000
    sym"@constant"                         { Constant }, -- @constant      xxx links to Constant
    luaConstant                            { Constant }, -- luaConstant    xxx links to Constant
    Number                                 { bg="#000000", fg="#ff0000", }, -- Number         xxx ctermfg=196 ctermbg=16 guifg=#ff0000 guibg=#000000
    Character                              { Number }, -- Character      xxx links to Number
    Float                                  { Number }, -- Float          xxx links to Number
    Tag                                    { Number }, -- Tag            xxx links to Number
    sym"@number"                           { Number }, -- @number        xxx links to Number
    NvimNumber                             { Number }, -- NvimNumber     xxx links to Number
    vimNumber                              { Number }, -- vimNumber      xxx links to Number
    vimMark                                { Number }, -- vimMark        xxx links to Number
    vimHiNmbr                              { Number }, -- vimHiNmbr      xxx links to Number
    luaNumber                              { Number }, -- luaNumber      xxx links to Number
    Identifier                             { fg="#40ffff", }, -- Identifier     xxx cterm=bold ctermfg=14 guifg=#40ffff
    sym"@parameter"                        { Identifier }, -- @parameter     xxx links to Identifier
    sym"@field"                            { Identifier }, -- @field         xxx links to Identifier
    sym"@property"                         { Identifier }, -- @property      xxx links to Identifier
    sym"@variable"                         { Identifier }, -- @variable      xxx links to Identifier
    sym"@namespace"                        { Identifier }, -- @namespace     xxx links to Identifier
    sym"@lsp.type.variable"                { Identifier }, -- @lsp.type.variable xxx links to Identifier
    NvimIdentifier                         { Identifier }, -- NvimIdentifier xxx links to Identifier
    vimVar                                 { Identifier }, -- vimVar         xxx links to Identifier
    vimSpecFile                            { Identifier }, -- vimSpecFile    xxx links to Identifier
    vimFuncVar                             { Identifier }, -- vimFuncVar     xxx links to Identifier
    luaFunc                                { Identifier }, -- luaFunc        xxx links to Identifier
    Statement                              { gui="bold", fg="#ffff60", }, -- Statement      xxx ctermfg=11 gui=bold guifg=#ffff60
    vimCommand                             { Statement }, -- vimCommand     xxx links to Statement
    vimSetSep                              { Statement }, -- vimSetSep      xxx links to Statement
    vimSearchDelim                         { Statement }, -- vimSearchDelim xxx links to Statement
    luaStatement                           { Statement }, -- luaStatement   xxx links to Statement
    vimKeyword                             { Statement }, -- vimKeyword     xxx links to Statement
    vimStatement                           { Statement }, -- vimStatement   xxx links to Statement
    Keyword                                { bg="#000000", fg="#eeeeee", }, -- Keyword        xxx ctermfg=255 ctermbg=16 guifg=#eeeeee guibg=#000000
    Function                               { Keyword }, -- Function       xxx links to Keyword
    Conditional                            { Keyword }, -- Conditional    xxx links to Keyword
    Repeat                                 { Keyword }, -- Repeat         xxx links to Keyword
    Label                                  { Keyword }, -- Label          xxx links to Keyword
    Operator                               { Keyword }, -- Operator       xxx links to Keyword
    Include                                { Keyword }, -- Include        xxx links to Keyword
    Define                                 { Keyword }, -- Define         xxx links to Keyword
    PreCondit                              { Keyword }, -- PreCondit      xxx links to Keyword
    StorageClass                           { Keyword }, -- StorageClass   xxx links to Keyword
    Structure                              { Keyword }, -- Structure      xxx links to Keyword
    Typedef                                { Keyword }, -- Typedef        xxx links to Keyword
    SpecialChar                            { Keyword }, -- SpecialChar    xxx links to Keyword
    sym"@keyword"                          { Keyword }, -- @keyword       xxx links to Keyword
    diffAdded                              { Keyword }, -- diffAdded      xxx links to Keyword
    diffCommon                             { Keyword }, -- diffCommon     xxx links to Keyword
    PreProc                                { fg="#ff80ff", }, -- PreProc        xxx ctermfg=81 guifg=#ff80ff
    sym"@preproc"                          { PreProc }, -- @preproc       xxx links to PreProc
    vimOption                              { PreProc }, -- vimOption      xxx links to PreProc
    vimEnvvar                              { PreProc }, -- vimEnvvar      xxx links to PreProc
    vimMenuName                            { PreProc }, -- vimMenuName    xxx links to PreProc
    vimHiAttrib                            { PreProc }, -- vimHiAttrib    xxx links to PreProc
    vimCommentTitle                        { PreProc }, -- vimCommentTitle xxx links to PreProc
    vimHLMod                               { PreProc }, -- vimHLMod       xxx links to PreProc
    Type                                   { gui="bold", fg="#60ff60", }, -- Type           xxx ctermfg=121 gui=bold guifg=#60ff60
    sym"@type"                             { Type }, -- @type          xxx links to Type
    sym"@lsp.type.type"                    { Type }, -- @lsp.type.type xxx links to Type
    NvimNumberPrefix                       { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOptionSigil                        { Type }, -- NvimOptionSigil xxx links to Type
    vimGroup                               { Type }, -- vimGroup       xxx links to Type
    vimType                                { Type }, -- vimType        xxx links to Type
    vimPattern                             { Type }, -- vimPattern     xxx links to Type
    vimAutoEvent                           { Type }, -- vimAutoEvent   xxx links to Type
    vimSynCase                             { Type }, -- vimSynCase     xxx links to Type
    vimSynReg                              { Type }, -- vimSynReg      xxx links to Type
    vimSyncC                               { Type }, -- vimSyncC       xxx links to Type
    vimSyncKey                             { Type }, -- vimSyncKey     xxx links to Type
    vimSyncNone                            { Type }, -- vimSyncNone    xxx links to Type
    vimHiTerm                              { Type }, -- vimHiTerm      xxx links to Type
    vimSpecial                             { Type }, -- vimSpecial     xxx links to Type
    NullLsInfoTitle                        { Type }, -- NullLsInfoTitle xxx links to Type
    LspInfoFiletype                        { Type }, -- LspInfoFiletype xxx links to Type
    Special                                { fg="orange", }, -- Special        xxx ctermfg=224 guifg=Orange
    sym"@constant.builtin"                 { Special }, -- @constant.builtin xxx links to Special
    sym"@function.builtin"                 { Special }, -- @function.builtin xxx links to Special
    sym"@constructor"                      { Special }, -- @constructor   xxx links to Special
    vimNotation                            { Special }, -- vimNotation    xxx links to Special
    vimContinue                            { Special }, -- vimContinue    xxx links to Special
    vimFuncSID                             { Special }, -- vimFuncSID     xxx links to Special
    vimUserAttrbCmpltFunc                  { Special }, -- vimUserAttrbCmpltFunc xxx links to Special
    vimEscape                              { Special }, -- vimEscape      xxx links to Special
    vimSubstFlags                          { Special }, -- vimSubstFlags  xxx links to Special
    vimLetHereDocStart                     { Special }, -- vimLetHereDocStart xxx links to Special
    vimLetHereDocStop                      { Special }, -- vimLetHereDocStop xxx links to Special
    vimAutoCmdMod                          { Special }, -- vimAutoCmdMod  xxx links to Special
    vimGroupSpecial                        { Special }, -- vimGroupSpecial xxx links to Special
    vimSynOption                           { Special }, -- vimSynOption   xxx links to Special
    DiagnosticError                        { fg="red", }, -- DiagnosticError xxx ctermfg=1 guifg=Red
    DiagnosticVirtualTextError             { DiagnosticError }, -- DiagnosticVirtualTextError xxx links to DiagnosticError
    DiagnosticFloatingError                { DiagnosticError }, -- DiagnosticFloatingError xxx links to DiagnosticError
    DiagnosticSignError                    { DiagnosticError }, -- DiagnosticSignError xxx links to DiagnosticError
    DiagnosticWarn                         { fg="orange", }, -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
    DiagnosticVirtualTextWarn              { DiagnosticWarn }, -- DiagnosticVirtualTextWarn xxx links to DiagnosticWarn
    DiagnosticFloatingWarn                 { DiagnosticWarn }, -- DiagnosticFloatingWarn xxx links to DiagnosticWarn
    DiagnosticSignWarn                     { DiagnosticWarn }, -- DiagnosticSignWarn xxx links to DiagnosticWarn
    DiagnosticInfo                         { fg="lightblue", }, -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
    DiagnosticVirtualTextInfo              { DiagnosticInfo }, -- DiagnosticVirtualTextInfo xxx links to DiagnosticInfo
    DiagnosticFloatingInfo                 { DiagnosticInfo }, -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
    DiagnosticSignInfo                     { DiagnosticInfo }, -- DiagnosticSignInfo xxx links to DiagnosticInfo
    DiagnosticHint                         { fg="lightgrey", }, -- DiagnosticHint xxx ctermfg=7 guifg=LightGrey
    DiagnosticVirtualTextHint              { DiagnosticHint }, -- DiagnosticVirtualTextHint xxx links to DiagnosticHint
    DiagnosticFloatingHint                 { DiagnosticHint }, -- DiagnosticFloatingHint xxx links to DiagnosticHint
    DiagnosticSignHint                     { DiagnosticHint }, -- DiagnosticSignHint xxx links to DiagnosticHint
    DiagnosticOk                           { fg="lightgreen", }, -- DiagnosticOk   xxx ctermfg=10 guifg=LightGreen
    DiagnosticVirtualTextOk                { DiagnosticOk }, -- DiagnosticVirtualTextOk xxx links to DiagnosticOk
    DiagnosticFloatingOk                   { DiagnosticOk }, -- DiagnosticFloatingOk xxx links to DiagnosticOk
    DiagnosticSignOk                       { DiagnosticOk }, -- DiagnosticSignOk xxx links to DiagnosticOk
    DiagnosticUnderlineError               { sp="red", gui="underline", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
    DiagnosticUnderlineWarn                { sp="orange", gui="underline", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
    DiagnosticUnderlineInfo                { sp="lightblue", gui="underline", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
    DiagnosticUnderlineHint                { sp="lightgrey", gui="underline", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
    DiagnosticUnderlineOk                  { sp="lightgreen", gui="underline", }, -- DiagnosticUnderlineOk xxx cterm=underline gui=underline guisp=LightGreen
    DiagnosticDeprecated                   { sp="red", gui="strikethrough", }, -- DiagnosticDeprecated xxx cterm=strikethrough gui=strikethrough guisp=Red
    Comment                                { bg="#000000", fg="#585858", }, -- Comment        xxx ctermfg=240 ctermbg=16 guifg=#585858 guibg=#000000
    DiagnosticUnnecessary                  { Comment }, -- DiagnosticUnnecessary xxx links to Comment
    sym"@text.literal"                     { Comment }, -- @text.literal  xxx links to Comment
    sym"@comment"                          { Comment }, -- @comment       xxx links to Comment
    diffRemoved                            { Comment }, -- diffRemoved    xxx links to Comment
    UfoFoldedEllipsis                      { Comment }, -- UfoFoldedEllipsis xxx links to Comment
    vimComment                             { Comment }, -- vimComment     xxx links to Comment
    vim9Comment                            { Comment }, -- vim9Comment    xxx links to Comment
    luaComment                             { Comment }, -- luaComment     xxx links to Comment
    vimScriptDelim                         { Comment }, -- vimScriptDelim xxx links to Comment
    CopilotAnnotation                      { Comment }, -- CopilotAnnotation xxx links to Comment
    CopilotSuggestion                      { Comment }, -- CopilotSuggestion xxx links to Comment
    LspInfoTip                             { Comment }, -- LspInfoTip     xxx links to Comment
    AerialPrivate                          { Comment }, -- AerialPrivate  xxx links to Comment
    AerialProtected                        { Comment }, -- AerialProtected xxx links to Comment
    Underlined                             { gui="underline", fg="#80a0ff", }, -- Underlined     xxx cterm=underline ctermfg=81 gui=underline guifg=#80a0ff
    sym"@text.uri"                         { Underlined }, -- @text.uri      xxx links to Underlined
    MatchParen                             { bg="#585858", fg="#000000", }, -- MatchParen     xxx ctermfg=16 ctermbg=240 guifg=#000000 guibg=#585858
    Ignore                                 { fg="bg", }, -- Ignore         xxx ctermfg=0 guifg=bg
    NvimInternalError                      { bg="red", fg="red", }, -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
    NvimFigureBrace                        { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimSingleQuotedUnknownEscape          { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSingleQuotedUnknownEscape   { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
    DevIconFennel                          { fg="#fff3d7", }, -- DevIconFennel  xxx ctermfg=230 guifg=#fff3d7
    DevIconBazelBuild                      { fg="#89e051", }, -- DevIconBazelBuild xxx ctermfg=113 guifg=#89e051
    DevIconTypeScriptReactTest             { fg="#1354bf", }, -- DevIconTypeScriptReactTest xxx ctermfg=26 guifg=#1354bf
    DevIconErb                             { fg="#701516", }, -- DevIconErb     xxx ctermfg=52 guifg=#701516
    DevIconJavaScriptReactTest             { fg="#20c2e3", }, -- DevIconJavaScriptReactTest xxx ctermfg=45 guifg=#20c2e3
    DevIconNswag                           { fg="#85ea2d", }, -- DevIconNswag   xxx ctermfg=112 guifg=#85ea2d
    DevIconEnv                             { fg="#faf743", }, -- DevIconEnv     xxx ctermfg=227 guifg=#faf743
    DevIconBashrc                          { fg="#89e051", }, -- DevIconBashrc  xxx ctermfg=113 guifg=#89e051
    DevIconOPUS                            { fg="#f88a02", }, -- DevIconOPUS    xxx ctermfg=208 guifg=#f88a02
    DevIconLicense                         { fg="#cbcb41", }, -- DevIconLicense xxx ctermfg=185 guifg=#cbcb41
    DevIconBmp                             { fg="#a074c4", }, -- DevIconBmp     xxx ctermfg=140 guifg=#a074c4
    DevIconBinaryGLTF                      { fg="#ffb13b", }, -- DevIconBinaryGLTF xxx ctermfg=214 guifg=#ffb13b
    DevIconPsd                             { fg="#519aba", }, -- DevIconPsd     xxx ctermfg=74 guifg=#519aba
    DevIconTcl                             { fg="#1e5cb3", }, -- DevIconTcl     xxx ctermfg=25 guifg=#1e5cb3
    DevIconSlim                            { fg="#e34c26", }, -- DevIconSlim    xxx ctermfg=196 guifg=#e34c26
    DevIconSuo                             { fg="#e37933", }, -- DevIconSuo     xxx ctermfg=166 guifg=#e37933
    DevIconPng                             { fg="#a074c4", }, -- DevIconPng     xxx ctermfg=140 guifg=#a074c4
    DevIconTempl                           { fg="#dbbd30", }, -- DevIconTempl   xxx ctermfg=178 guifg=#dbbd30
    DevIconWasm                            { fg="#5c4cdb", }, -- DevIconWasm    xxx ctermfg=62 guifg=#5c4cdb
    DevIconXls                             { fg="#207245", }, -- DevIconXls     xxx ctermfg=29 guifg=#207245
    DevIconXlsx                            { fg="#207245", }, -- DevIconXlsx    xxx ctermfg=29 guifg=#207245
    DevIconXcPlayground                    { fg="#e37933", }, -- DevIconXcPlayground xxx ctermfg=166 guifg=#e37933
    DevIconWebpack                         { fg="#519aba", }, -- DevIconWebpack xxx ctermfg=74 guifg=#519aba
    DevIconWebp                            { fg="#a074c4", }, -- DevIconWebp    xxx ctermfg=140 guifg=#a074c4
    DevIconWebm                            { fg="#fd971f", }, -- DevIconWebm    xxx ctermfg=208 guifg=#fd971f
    DevIconWav                             { fg="#66d8ef", }, -- DevIconWav     xxx ctermfg=45 guifg=#66d8ef
    DevIconStyl                            { fg="#8dc149", }, -- DevIconStyl    xxx ctermfg=113 guifg=#8dc149
    DevIconSql                             { fg="#dad8d8", }, -- DevIconSql     xxx ctermfg=188 guifg=#dad8d8
    DevIconRproj                           { fg="#358a5b", }, -- DevIconRproj   xxx ctermfg=29 guifg=#358a5b
    DevIconRlib                            { fg="#dea584", }, -- DevIconRlib    xxx ctermfg=216 guifg=#dea584
    DevIconPyo                             { fg="#ffe291", }, -- DevIconPyo     xxx ctermfg=222 guifg=#ffe291
    DevIconPyd                             { fg="#ffe291", }, -- DevIconPyd     xxx ctermfg=222 guifg=#ffe291
    DevIconPyc                             { fg="#ffe291", }, -- DevIconPyc     xxx ctermfg=222 guifg=#ffe291
    DevIconTypeScriptReactSpec             { fg="#1354bf", }, -- DevIconTypeScriptReactSpec xxx ctermfg=26 guifg=#1354bf
    DevIconPsb                             { fg="#519aba", }, -- DevIconPsb     xxx ctermfg=74 guifg=#519aba
    DevIconSpecTs                          { fg="#519aba", }, -- DevIconSpecTs  xxx ctermfg=74 guifg=#519aba
    DevIconLuau                            { fg="#00a2ff", }, -- DevIconLuau    xxx ctermfg=75 guifg=#00a2ff
    DevIconJavaScriptReactSpec             { fg="#20c2e3", }, -- DevIconJavaScriptReactSpec xxx ctermfg=45 guifg=#20c2e3
    DevIconOpenTypeFont                    { fg="#ececec", }, -- DevIconOpenTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconSpecJs                          { fg="#cbcb41", }, -- DevIconSpecJs  xxx ctermfg=185 guifg=#cbcb41
    DevIconMustache                        { fg="#e37933", }, -- DevIconMustache xxx ctermfg=166 guifg=#e37933
    DevIconMOV                             { fg="#fd971f", }, -- DevIconMOV     xxx ctermfg=208 guifg=#fd971f
    DevIconMkv                             { fg="#fd971f", }, -- DevIconMkv     xxx ctermfg=208 guifg=#fd971f
    DevIconMint                            { fg="#87c095", }, -- DevIconMint    xxx ctermfg=108 guifg=#87c095
    DevIconJava                            { fg="#cc3e44", }, -- DevIconJava    xxx ctermfg=167 guifg=#cc3e44
    DevIconM4V                             { fg="#fd971f", }, -- DevIconM4V     xxx ctermfg=208 guifg=#fd971f
    DevIconM4A                             { fg="#66d8ef", }, -- DevIconM4A     xxx ctermfg=45 guifg=#66d8ef
    DevIconMaterial                        { fg="#b83998", }, -- DevIconMaterial xxx ctermfg=163 guifg=#b83998
    DevIconJpg                             { fg="#a074c4", }, -- DevIconJpg     xxx ctermfg=140 guifg=#a074c4
    DevIconBzl                             { fg="#89e051", }, -- DevIconBzl     xxx ctermfg=113 guifg=#89e051
    DevIconIco                             { fg="#cbcb41", }, -- DevIconIco     xxx ctermfg=185 guifg=#cbcb41
    DevIconGulpfile                        { fg="#cc3e44", }, -- DevIconGulpfile xxx ctermfg=167 guifg=#cc3e44
    DevIconGruntfile                       { fg="#e37933", }, -- DevIconGruntfile xxx ctermfg=166 guifg=#e37933
    DevIconGodotProject                    { fg="#6d8086", }, -- DevIconGodotProject xxx ctermfg=66 guifg=#6d8086
    DevIconGif                             { fg="#a074c4", }, -- DevIconGif     xxx ctermfg=140 guifg=#a074c4
    DevIconFsscript                        { fg="#519aba", }, -- DevIconFsscript xxx ctermfg=74 guifg=#519aba
    DevIconFlac                            { fg="#66d8ef", }, -- DevIconFlac    xxx ctermfg=45 guifg=#66d8ef
    DevIconEjs                             { fg="#cbcb41", }, -- DevIconEjs     xxx ctermfg=185 guifg=#cbcb41
    DevIconTextResource                    { fg="#cbcb41", }, -- DevIconTextResource xxx ctermfg=185 guifg=#cbcb41
    DevIconTextScene                       { fg="#a074c4", }, -- DevIconTextScene xxx ctermfg=140 guifg=#a074c4
    DevIconTs                              { fg="#519aba", }, -- DevIconTs      xxx ctermfg=74 guifg=#519aba
    DevIconZshprofile                      { fg="#89e051", }, -- DevIconZshprofile xxx ctermfg=113 guifg=#89e051
    DevIconCson                            { fg="#cbcb41", }, -- DevIconCson    xxx ctermfg=185 guifg=#cbcb41
    DevIconCp                              { fg="#519aba", }, -- DevIconCp      xxx ctermfg=74 guifg=#519aba
    DevIconDockerfile                      { fg="#458ee6", }, -- DevIconDockerfile xxx ctermfg=68 guifg=#458ee6
    DevIconAac                             { fg="#66d8ef", }, -- DevIconAac     xxx ctermfg=45 guifg=#66d8ef
    DevIconFsi                             { fg="#519aba", }, -- DevIconFsi     xxx ctermfg=74 guifg=#519aba
    DevIconVagrantfile                     { fg="#1563ff", }, -- DevIconVagrantfile xxx ctermfg=27 guifg=#1563ff
    DevIconCobol                           { fg="#005ca5", }, -- DevIconCobol   xxx ctermfg=25 guifg=#005ca5
    DevIconGemfile                         { fg="#701516", }, -- DevIconGemfile xxx ctermfg=52 guifg=#701516
    DevIconBrewfile                        { fg="#701516", }, -- DevIconBrewfile xxx ctermfg=52 guifg=#701516
    DevIconMakefile                        { fg="#6d8086", }, -- DevIconMakefile xxx ctermfg=66 guifg=#6d8086
    DevIconFsharp                          { fg="#519aba", }, -- DevIconFsharp  xxx ctermfg=74 guifg=#519aba
    DevIconEditorConfig                    { fg="#ffffff", }, -- DevIconEditorConfig xxx ctermfg=231 guifg=#ffffff
    DevIconClojureC                        { fg="#8dc149", }, -- DevIconClojureC xxx ctermfg=113 guifg=#8dc149
    DevIconClojure                         { fg="#8dc149", }, -- DevIconClojure xxx ctermfg=113 guifg=#8dc149
    DevIconRazorPage                       { fg="#512bd4", }, -- DevIconRazorPage xxx ctermfg=56 guifg=#512bd4
    DevIconNPMrc                           { fg="#e8274b", }, -- DevIconNPMrc   xxx ctermfg=197 guifg=#e8274b
    DevIconHurl                            { fg="#ff0288", }, -- DevIconHurl    xxx ctermfg=198 guifg=#ff0288
    DevIconFortran                         { fg="#734f96", }, -- DevIconFortran xxx ctermfg=97 guifg=#734f96
    DevIconArch                            { fg="#0f94d2", }, -- DevIconArch    xxx ctermfg=67 guifg=#0f94d2
    DevIconHuff                            { fg="#4242c7", }, -- DevIconHuff    xxx ctermfg=56 guifg=#4242c7
    DevIconZorin                           { fg="#14a1e8", }, -- DevIconZorin   xxx ctermfg=39 guifg=#14a1e8
    DevIconPy                              { fg="#ffbc03", }, -- DevIconPy      xxx ctermfg=214 guifg=#ffbc03
    DevIconPyx                             { fg="#5aa7e4", }, -- DevIconPyx     xxx ctermfg=39 guifg=#5aa7e4
    DevIconJs                              { fg="#f1f134", }, -- DevIconJs      xxx ctermfg=227 guifg=#f1f134
    DevIconMjs                             { fg="#f1f134", }, -- DevIconMjs     xxx ctermfg=227 guifg=#f1f134
    DevIconCsh                             { fg="#4d5a5e", }, -- DevIconCsh     xxx ctermfg=240 guifg=#4d5a5e
    DevIconC                               { fg="#599eff", }, -- DevIconC       xxx ctermfg=111 guifg=#599eff
    DevIconSolus                           { fg="#4b5163", }, -- DevIconSolus   xxx ctermfg=239 guifg=#4b5163
    DevIconPsScriptfile                    { fg="#4273ca", }, -- DevIconPsScriptfile xxx ctermfg=68 guifg=#4273ca
    DevIconEdn                             { fg="#519aba", }, -- DevIconEdn     xxx ctermfg=74 guifg=#519aba
    DevIconHtm                             { fg="#e34c26", }, -- DevIconHtm     xxx ctermfg=196 guifg=#e34c26
    DevIconSlackware                       { fg="#475fa9", }, -- DevIconSlackware xxx ctermfg=61 guifg=#475fa9
    DevIconBazel                           { fg="#89e051", }, -- DevIconBazel   xxx ctermfg=113 guifg=#89e051
    DevIconHtml                            { fg="#e44d26", }, -- DevIconHtml    xxx ctermfg=196 guifg=#e44d26
    DevIconSabayon                         { fg="#c6c6c6", }, -- DevIconSabayon xxx ctermfg=251 guifg=#c6c6c6
    DevIconTerminal                        { fg="#31b53e", }, -- DevIconTerminal xxx ctermfg=34 guifg=#31b53e
    DevIconRockyLinux                      { fg="#0fb37d", }, -- DevIconRockyLinux xxx ctermfg=36 guifg=#0fb37d
    DevIconBibTeX                          { fg="#cbcb41", }, -- DevIconBibTeX  xxx ctermfg=185 guifg=#cbcb41
    DevIconAi                              { fg="#cbcb41", }, -- DevIconAi      xxx ctermfg=185 guifg=#cbcb41
    DevIconCPlusPlus                       { fg="#f34b7d", }, -- DevIconCPlusPlus xxx ctermfg=204 guifg=#f34b7d
    DevIconRedhat                          { fg="#ee0000", }, -- DevIconRedhat  xxx ctermfg=196 guifg=#ee0000
    DevIconConfigRu                        { fg="#701516", }, -- DevIconConfigRu xxx ctermfg=52 guifg=#701516
    DevIconLess                            { fg="#563d7c", }, -- DevIconLess    xxx ctermfg=54 guifg=#563d7c
    DevIconGo                              { fg="#519aba", }, -- DevIconGo      xxx ctermfg=74 guifg=#519aba
    DevIconDiff                            { fg="#41535b", }, -- DevIconDiff    xxx ctermfg=239 guifg=#41535b
    DevIconSig                             { fg="#e37933", }, -- DevIconSig     xxx ctermfg=166 guifg=#e37933
    DevIconClojureDart                     { fg="#519aba", }, -- DevIconClojureDart xxx ctermfg=74 guifg=#519aba
    DevIconPop_OS                          { fg="#48b9c7", }, -- DevIconPop_OS  xxx ctermfg=73 guifg=#48b9c7
    DevIconExe                             { fg="#9f0500", }, -- DevIconExe     xxx ctermfg=124 guifg=#9f0500
    DevIconHeex                            { fg="#a074c4", }, -- DevIconHeex    xxx ctermfg=140 guifg=#a074c4
    DevIconPp                              { fg="#ffa61a", }, -- DevIconPp      xxx ctermfg=214 guifg=#ffa61a
    DevIconopenSUSE                        { fg="#6fb424", }, -- DevIconopenSUSE xxx ctermfg=70 guifg=#6fb424
    DevIconKotlin                          { fg="#7f52ff", }, -- DevIconKotlin  xxx ctermfg=99 guifg=#7f52ff
    DevIconKotlinScript                    { fg="#7f52ff", }, -- DevIconKotlinScript xxx ctermfg=99 guifg=#7f52ff
    DevIconJl                              { fg="#a270ba", }, -- DevIconJl      xxx ctermfg=133 guifg=#a270ba
    DevIconOpenBSD                         { fg="#000000", }, -- DevIconOpenBSD xxx ctermfg=16 guifg=#000000
    DevIconJson                            { fg="#cbcb41", }, -- DevIconJson    xxx ctermfg=185 guifg=#cbcb41
    DevIconNixOS                           { fg="#7ab1db", }, -- DevIconNixOS   xxx ctermfg=110 guifg=#7ab1db
    DevIconJson5                           { fg="#cbcb41", }, -- DevIconJson5   xxx ctermfg=185 guifg=#cbcb41
    DevIconGemspec                         { fg="#701516", }, -- DevIconGemspec xxx ctermfg=52 guifg=#701516
    DevIconAzureCli                        { fg="#0078d4", }, -- DevIconAzureCli xxx ctermfg=32 guifg=#0078d4
    DevIconRs                              { fg="#dea584", }, -- DevIconRs      xxx ctermfg=216 guifg=#dea584
    DevIconH                               { fg="#a074c4", }, -- DevIconH       xxx ctermfg=140 guifg=#a074c4
    DevIconBat                             { fg="#c1f12e", }, -- DevIconBat     xxx ctermfg=191 guifg=#c1f12e
    DevIconMageia                          { fg="#2397d4", }, -- DevIconMageia  xxx ctermfg=67 guifg=#2397d4
    DevIconBabelrc                         { fg="#cbcb41", }, -- DevIconBabelrc xxx ctermfg=185 guifg=#cbcb41
    DevIconsbt                             { fg="#cc3e44", }, -- DevIconsbt     xxx ctermfg=167 guifg=#cc3e44
    DevIconScala                           { fg="#cc3e44", }, -- DevIconScala   xxx ctermfg=167 guifg=#cc3e44
    DevIconLua                             { fg="#51a0cf", }, -- DevIconLua     xxx ctermfg=74 guifg=#51a0cf
    DevIconScheme                          { fg="#eeeeee", }, -- DevIconScheme  xxx ctermfg=255 guifg=#eeeeee
    DevIconKali                            { fg="#ffffff", }, -- DevIconKali    xxx ctermfg=231 guifg=#ffffff
    DevIconBazelWorkspace                  { fg="#89e051", }, -- DevIconBazelWorkspace xxx ctermfg=113 guifg=#89e051
    DevIconVHDL                            { fg="#019833", }, -- DevIconVHDL    xxx ctermfg=28 guifg=#019833
    DevIconScss                            { fg="#f55385", }, -- DevIconScss    xxx ctermfg=204 guifg=#f55385
    DevIconIllumos                         { fg="#ff430f", }, -- DevIconIllumos xxx ctermfg=196 guifg=#ff430f
    DevIconTSConfig                        { fg="#519aba", }, -- DevIconTSConfig xxx ctermfg=74 guifg=#519aba
    DevIconEpp                             { fg="#ffa61a", }, -- DevIconEpp     xxx ctermfg=214 guifg=#ffa61a
    DevIconGuix                            { fg="#ffcc00", }, -- DevIconGuix    xxx ctermfg=220 guifg=#ffcc00
    DevIconSvelteConfig                    { fg="#ff3e00", }, -- DevIconSvelteConfig xxx ctermfg=196 guifg=#ff3e00
    DevIconRakefile                        { fg="#701516", }, -- DevIconRakefile xxx ctermfg=52 guifg=#701516
    DevIconAppleScript                     { fg="#6d8085", }, -- DevIconAppleScript xxx ctermfg=66 guifg=#6d8085
    sym"DevIconPy.typed"                   { fg="#ffbc03", }, -- DevIconPy.typed xxx ctermfg=214 guifg=#ffbc03
    DevIconConfiguration                   { fg="#ececec", }, -- DevIconConfiguration xxx ctermfg=255 guifg=#ececec
    DevIconPackageLockJson                 { fg="#7a0d21", }, -- DevIconPackageLockJson xxx ctermfg=52 guifg=#7a0d21
    DevIconPackageJson                     { fg="#e8274b", }, -- DevIconPackageJson xxx ctermfg=197 guifg=#e8274b
    DevIconZshrc                           { fg="#89e051", }, -- DevIconZshrc   xxx ctermfg=113 guifg=#89e051
    DevIconD                               { fg="#427819", }, -- DevIconD       xxx ctermfg=28 guifg=#427819
    DevIconFreeBSD                         { fg="#c90f02", }, -- DevIconFreeBSD xxx ctermfg=160 guifg=#c90f02
    DevIconSolidity                        { fg="#519aba", }, -- DevIconSolidity xxx ctermfg=74 guifg=#519aba
    DevIconFedora                          { fg="#072a5e", }, -- DevIconFedora  xxx ctermfg=17 guifg=#072a5e
    DevIconLeex                            { fg="#a074c4", }, -- DevIconLeex    xxx ctermfg=140 guifg=#a074c4
    DevIconEndeavour                       { fg="#7b3db9", }, -- DevIconEndeavour xxx ctermfg=91 guifg=#7b3db9
    DevIconGitAttributes                   { fg="#41535b", }, -- DevIconGitAttributes xxx ctermfg=239 guifg=#41535b
    DevIconCMakeLists                      { fg="#6d8086", }, -- DevIconCMakeLists xxx ctermfg=66 guifg=#6d8086
    DevIconGitConfig                       { fg="#41535b", }, -- DevIconGitConfig xxx ctermfg=239 guifg=#41535b
    DevIconSln                             { fg="#854cc7", }, -- DevIconSln     xxx ctermfg=98 guifg=#854cc7
    DevIconVimrc                           { fg="#019833", }, -- DevIconVimrc   xxx ctermfg=28 guifg=#019833
    DevIconGvimrc                          { fg="#019833", }, -- DevIconGvimrc  xxx ctermfg=28 guifg=#019833
    DevIconFish                            { fg="#4d5a5e", }, -- DevIconFish    xxx ctermfg=240 guifg=#4d5a5e
    DevIconDeepin                          { fg="#2ca7f8", }, -- DevIconDeepin  xxx ctermfg=39 guifg=#2ca7f8
    DevIconSettingsJson                    { fg="#854cc7", }, -- DevIconSettingsJson xxx ctermfg=98 guifg=#854cc7
    DevIconDebian                          { fg="#a80030", }, -- DevIconDebian  xxx ctermfg=88 guifg=#a80030
    DevIconNPMIgnore                       { fg="#e8274b", }, -- DevIconNPMIgnore xxx ctermfg=197 guifg=#e8274b
    DevIconLuaurc                          { fg="#00a2ff", }, -- DevIconLuaurc  xxx ctermfg=75 guifg=#00a2ff
    DevIconGitlabCI                        { fg="#e24329", }, -- DevIconGitlabCI xxx ctermfg=196 guifg=#e24329
    DevIconBudgie                          { fg="#ffffff", }, -- DevIconBudgie  xxx ctermfg=231 guifg=#ffffff
    DevIconIni                             { fg="#6d8086", }, -- DevIconIni     xxx ctermfg=66 guifg=#6d8086
    DevIconArtix                           { fg="#41b4d7", }, -- DevIconArtix   xxx ctermfg=38 guifg=#41b4d7
    DevIconEslintIgnore                    { fg="#4b32c3", }, -- DevIconEslintIgnore xxx ctermfg=56 guifg=#4b32c3
    DevIconAOSC                            { fg="#000000", }, -- DevIconAOSC    xxx ctermfg=16 guifg=#000000
    DevIconElm                             { fg="#519aba", }, -- DevIconElm     xxx ctermfg=74 guifg=#519aba
    DevIconAlpine                          { fg="#0d597f", }, -- DevIconAlpine  xxx ctermfg=24 guifg=#0d597f
    DevIconDsStore                         { fg="#41535b", }, -- DevIconDsStore xxx ctermfg=239 guifg=#41535b
    DevIconSvelte                          { fg="#ff3e00", }, -- DevIconSvelte  xxx ctermfg=196 guifg=#ff3e00
    DevIconSwift                           { fg="#e37933", }, -- DevIconSwift   xxx ctermfg=166 guifg=#e37933
    DevIconSystemVerilog                   { fg="#019833", }, -- DevIconSystemVerilog xxx ctermfg=28 guifg=#019833
    DevIconWindows                         { fg="#00a4ef", }, -- DevIconWindows xxx ctermfg=39 guifg=#00a4ef
    DevIconBash                            { fg="#89e051", }, -- DevIconBash    xxx ctermfg=113 guifg=#89e051
    DevIconApple                           { fg="#a2aaad", }, -- DevIconApple   xxx ctermfg=248 guifg=#a2aaad
    DevIconTFVars                          { fg="#5f43e9", }, -- DevIconTFVars  xxx ctermfg=93 guifg=#5f43e9
    DevIconVoid                            { fg="#295340", }, -- DevIconVoid    xxx ctermfg=23 guifg=#295340
    DevIconSvg                             { fg="#ffb13b", }, -- DevIconSvg     xxx ctermfg=214 guifg=#ffb13b
    DevIconHrl                             { fg="#b83998", }, -- DevIconHrl     xxx ctermfg=163 guifg=#b83998
    DevIconErl                             { fg="#b83998", }, -- DevIconErl     xxx ctermfg=163 guifg=#b83998
    DevIconTsx                             { fg="#1354bf", }, -- DevIconTsx     xxx ctermfg=26 guifg=#1354bf
    DevIconExs                             { fg="#a074c4", }, -- DevIconExs     xxx ctermfg=140 guifg=#a074c4
    DevIconElf                             { fg="#9f0500", }, -- DevIconElf     xxx ctermfg=124 guifg=#9f0500
    DevIconEex                             { fg="#a074c4", }, -- DevIconEex     xxx ctermfg=140 guifg=#a074c4
    DevIconLhs                             { fg="#a074c4", }, -- DevIconLhs     xxx ctermfg=140 guifg=#a074c4
    DevIconLiquid                          { fg="#95bf47", }, -- DevIconLiquid  xxx ctermfg=106 guifg=#95bf47
    DevIconVue                             { fg="#8dc149", }, -- DevIconVue     xxx ctermfg=113 guifg=#8dc149
    DevIconDart                            { fg="#03589c", }, -- DevIconDart    xxx ctermfg=25 guifg=#03589c
    DevIconXul                             { fg="#e37933", }, -- DevIconXul     xxx ctermfg=166 guifg=#e37933
    DevIconToml                            { fg="#ffffff", }, -- DevIconToml    xxx ctermfg=231 guifg=#ffffff
    DevIconRss                             { fg="#fb9d3b", }, -- DevIconRss     xxx ctermfg=215 guifg=#fb9d3b
    DevIconDevuan                          { fg="#404a52", }, -- DevIconDevuan  xxx ctermfg=238 guifg=#404a52
    DevIconCsv                             { fg="#89e051", }, -- DevIconCsv     xxx ctermfg=113 guifg=#89e051
    DevIconCss                             { fg="#42a5f5", }, -- DevIconCss     xxx ctermfg=75 guifg=#42a5f5
    DevIconCSharpProject                   { fg="#512bd4", }, -- DevIconCSharpProject xxx ctermfg=56 guifg=#512bd4
    DevIconCentos                          { fg="#a2518d", }, -- DevIconCentos  xxx ctermfg=132 guifg=#a2518d
    DevIconLinux                           { fg="#000000", }, -- DevIconLinux   xxx ctermfg=16 guifg=#000000
    DevIconTex                             { fg="#3d6117", }, -- DevIconTex     xxx ctermfg=22 guifg=#3d6117
    DevIconCs                              { fg="#596706", }, -- DevIconCs      xxx ctermfg=58 guifg=#596706
    DevIconUbuntu                          { fg="#dd4814", }, -- DevIconUbuntu  xxx ctermfg=196 guifg=#dd4814
    DevIconMts                             { fg="#519aba", }, -- DevIconMts     xxx ctermfg=74 guifg=#519aba
    DevIconCrystal                         { fg="#c8c8c8", }, -- DevIconCrystal xxx ctermfg=251 guifg=#c8c8c8
    DevIconJsonc                           { fg="#cbcb41", }, -- DevIconJsonc   xxx ctermfg=185 guifg=#cbcb41
    DevIconYml                             { fg="#6d8086", }, -- DevIconYml     xxx ctermfg=66 guifg=#6d8086
    DevIconDb                              { fg="#dad8d8", }, -- DevIconDb      xxx ctermfg=188 guifg=#dad8d8
    DevIconElementary                      { fg="#5890c2", }, -- DevIconElementary xxx ctermfg=67 guifg=#5890c2
    DevIconTwig                            { fg="#8dc149", }, -- DevIconTwig    xxx ctermfg=113 guifg=#8dc149
    DevIconZshenv                          { fg="#89e051", }, -- DevIconZshenv  xxx ctermfg=113 guifg=#89e051
    DevIconOgg                             { fg="#66d8ef", }, -- DevIconOgg     xxx ctermfg=45 guifg=#66d8ef
    DevIconZig                             { fg="#f69a1b", }, -- DevIconZig     xxx ctermfg=172 guifg=#f69a1b
    DevIconHxx                             { fg="#a074c4", }, -- DevIconHxx     xxx ctermfg=140 guifg=#a074c4
    DevIconNim                             { fg="#f3d400", }, -- DevIconNim     xxx ctermfg=220 guifg=#f3d400
    DevIconRaspberryPiOS                   { fg="#be1848", }, -- DevIconRaspberryPiOS xxx ctermfg=161 guifg=#be1848
    DevIconCxx                             { fg="#519aba", }, -- DevIconCxx     xxx ctermfg=74 guifg=#519aba
    DevIconEslintrc                        { fg="#4b32c3", }, -- DevIconEslintrc xxx ctermfg=56 guifg=#4b32c3
    DevIconManjaro                         { fg="#33b959", }, -- DevIconManjaro xxx ctermfg=35 guifg=#33b959
    DevIconRmd                             { fg="#519aba", }, -- DevIconRmd     xxx ctermfg=74 guifg=#519aba
    DevIconHh                              { fg="#a074c4", }, -- DevIconHh      xxx ctermfg=140 guifg=#a074c4
    DevIconCpp                             { fg="#519aba", }, -- DevIconCpp     xxx ctermfg=74 guifg=#519aba
    DevIconFavicon                         { fg="#cbcb41", }, -- DevIconFavicon xxx ctermfg=185 guifg=#cbcb41
    DevIconReScriptInterface               { fg="#f55385", }, -- DevIconReScriptInterface xxx ctermfg=204 guifg=#f55385
    DevIconReScript                        { fg="#cc3e44", }, -- DevIconReScript xxx ctermfg=167 guifg=#cc3e44
    DevIconZsh                             { fg="#89e051", }, -- DevIconZsh     xxx ctermfg=113 guifg=#89e051
    DevIconJpegXl                          { fg="#a074c4", }, -- DevIconJpegXl  xxx ctermfg=140 guifg=#a074c4
    DevIconSml                             { fg="#e37933", }, -- DevIconSml     xxx ctermfg=166 guifg=#e37933
    DevIconEmbeddedOpenTypeFont            { fg="#ececec", }, -- DevIconEmbeddedOpenTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconImportConfiguration             { fg="#ececec", }, -- DevIconImportConfiguration xxx ctermfg=255 guifg=#ececec
    DevIconPyi                             { fg="#ffbc03", }, -- DevIconPyi     xxx ctermfg=214 guifg=#ffbc03
    DevIconConf                            { fg="#6d8086", }, -- DevIconConf    xxx ctermfg=66 guifg=#6d8086
    DevIconMd                              { fg="#ffffff", }, -- DevIconMd      xxx ctermfg=231 guifg=#ffffff
    DevIconPxd                             { fg="#5aa7e4", }, -- DevIconPxd     xxx ctermfg=39 guifg=#5aa7e4
    DevIconPsManifestfile                  { fg="#6975c4", }, -- DevIconPsManifestfile xxx ctermfg=68 guifg=#6975c4
    DevIconCjs                             { fg="#f1f134", }, -- DevIconCjs     xxx ctermfg=227 guifg=#f1f134
    DevIconQuery                           { fg="#90a850", }, -- DevIconQuery   xxx ctermfg=107 guifg=#90a850
    DevIconGraphQL                         { fg="#e535ab", }, -- DevIconGraphQL xxx ctermfg=199 guifg=#e535ab
    DevIconKsh                             { fg="#4d5a5e", }, -- DevIconKsh     xxx ctermfg=240 guifg=#4d5a5e
    DevIconHs                              { fg="#a074c4", }, -- DevIconHs      xxx ctermfg=140 guifg=#a074c4
    DevIconGitLogo                         { fg="#f14c28", }, -- DevIconGitLogo xxx ctermfg=196 guifg=#f14c28
    DevIconGDScript                        { fg="#6d8086", }, -- DevIconGDScript xxx ctermfg=66 guifg=#6d8086
    DevIconDoc                             { fg="#185abd", }, -- DevIconDoc     xxx ctermfg=26 guifg=#185abd
    DevIconFsx                             { fg="#519aba", }, -- DevIconFsx     xxx ctermfg=74 guifg=#519aba
    DevIconFs                              { fg="#519aba", }, -- DevIconFs      xxx ctermfg=74 guifg=#519aba
    DevIconPhp                             { fg="#a074c4", }, -- DevIconPhp     xxx ctermfg=140 guifg=#a074c4
    DevIconOrgMode                         { fg="#77aa99", }, -- DevIconOrgMode xxx ctermfg=73 guifg=#77aa99
    DevIconCts                             { fg="#519aba", }, -- DevIconCts     xxx ctermfg=74 guifg=#519aba
    DevIconGitCommit                       { fg="#41535b", }, -- DevIconGitCommit xxx ctermfg=239 guifg=#41535b
    DevIconVala                            { fg="#7239b3", }, -- DevIconVala    xxx ctermfg=91 guifg=#7239b3
    DevIconNodeModules                     { fg="#e8274b", }, -- DevIconNodeModules xxx ctermfg=197 guifg=#e8274b
    DevIconCoffee                          { fg="#cbcb41", }, -- DevIconCoffee  xxx ctermfg=185 guifg=#cbcb41
    DevIconClojureJS                       { fg="#519aba", }, -- DevIconClojureJS xxx ctermfg=74 guifg=#519aba
    DevIconMdx                             { fg="#519aba", }, -- DevIconMdx     xxx ctermfg=74 guifg=#519aba
    DevIconMotoko                          { fg="#9772fb", }, -- DevIconMotoko  xxx ctermfg=135 guifg=#9772fb
    DevIconPm                              { fg="#519aba", }, -- DevIconPm      xxx ctermfg=74 guifg=#519aba
    DevIconPdf                             { fg="#b30b00", }, -- DevIconPdf     xxx ctermfg=124 guifg=#b30b00
    DevIconDump                            { fg="#dad8d8", }, -- DevIconDump    xxx ctermfg=188 guifg=#dad8d8
    DevIconJsx                             { fg="#20c2e3", }, -- DevIconJsx     xxx ctermfg=45 guifg=#20c2e3
    DevIconApp                             { fg="#9f0500", }, -- DevIconApp     xxx ctermfg=124 guifg=#9f0500
    DevIconSass                            { fg="#f55385", }, -- DevIconSass    xxx ctermfg=204 guifg=#f55385
    DevIconTxt                             { fg="#89e051", }, -- DevIconTxt     xxx ctermfg=113 guifg=#89e051
    DevIconGitModules                      { fg="#41535b", }, -- DevIconGitModules xxx ctermfg=239 guifg=#41535b
    DevIconGitIgnore                       { fg="#41535b", }, -- DevIconGitIgnore xxx ctermfg=239 guifg=#41535b
    DevIconTor                             { fg="#519aba", }, -- DevIconTor     xxx ctermfg=74 guifg=#519aba
    DevIconMarkdown                        { fg="#519aba", }, -- DevIconMarkdown xxx ctermfg=74 guifg=#519aba
    DevIconXaml                            { fg="#512bd4", }, -- DevIconXaml    xxx ctermfg=56 guifg=#512bd4
    DevIconYaml                            { fg="#6d8086", }, -- DevIconYaml    xxx ctermfg=66 guifg=#6d8086
    DevIconTerraform                       { fg="#5f43e9", }, -- DevIconTerraform xxx ctermfg=93 guifg=#5f43e9
    DevIconVim                             { fg="#019833", }, -- DevIconVim     xxx ctermfg=28 guifg=#019833
    DevIconAvif                            { fg="#a074c4", }, -- DevIconAvif    xxx ctermfg=140 guifg=#a074c4
    DevIconProcfile                        { fg="#a074c4", }, -- DevIconProcfile xxx ctermfg=140 guifg=#a074c4
    DevIconR                               { fg="#2266ba", }, -- DevIconR       xxx ctermfg=25 guifg=#2266ba
    DevIconMixLock                         { fg="#a074c4", }, -- DevIconMixLock xxx ctermfg=140 guifg=#a074c4
    DevIconAwk                             { fg="#4d5a5e", }, -- DevIconAwk     xxx ctermfg=240 guifg=#4d5a5e
    DevIconMl                              { fg="#e37933", }, -- DevIconMl      xxx ctermfg=166 guifg=#e37933
    DevIconMli                             { fg="#e37933", }, -- DevIconMli     xxx ctermfg=166 guifg=#e37933
    DevIconDesktopEntry                    { fg="#563d7c", }, -- DevIconDesktopEntry xxx ctermfg=54 guifg=#563d7c
    DevIconBashProfile                     { fg="#89e051", }, -- DevIconBashProfile xxx ctermfg=113 guifg=#89e051
    DevIconLog                             { fg="#ffffff", }, -- DevIconLog     xxx ctermfg=231 guifg=#ffffff
    DevIconPackedResource                  { fg="#6d8086", }, -- DevIconPackedResource xxx ctermfg=66 guifg=#6d8086
    DevIconTestJs                          { fg="#cbcb41", }, -- DevIconTestJs  xxx ctermfg=185 guifg=#cbcb41
    DevIconJpeg                            { fg="#a074c4", }, -- DevIconJpeg    xxx ctermfg=140 guifg=#a074c4
    DevIconTestTs                          { fg="#519aba", }, -- DevIconTestTs  xxx ctermfg=74 guifg=#519aba
    DevIconDropbox                         { fg="#0061fe", }, -- DevIconDropbox xxx ctermfg=27 guifg=#0061fe
    DevIconRake                            { fg="#701516", }, -- DevIconRake    xxx ctermfg=52 guifg=#701516
    DevIconVerilog                         { fg="#019833", }, -- DevIconVerilog xxx ctermfg=28 guifg=#019833
    DevIconWebmanifest                     { fg="#f1e05a", }, -- DevIconWebmanifest xxx ctermfg=185 guifg=#f1e05a
    DevIconRb                              { fg="#701516", }, -- DevIconRb      xxx ctermfg=52 guifg=#701516
    DevIconDrools                          { fg="#ffafaf", }, -- DevIconDrools  xxx ctermfg=217 guifg=#ffafaf
    DevIconXml                             { fg="#e37933", }, -- DevIconXml     xxx ctermfg=166 guifg=#e37933
    DevIconDocx                            { fg="#185abd", }, -- DevIconDocx    xxx ctermfg=26 guifg=#185abd
    DevIconVlang                           { fg="#5d87bf", }, -- DevIconVlang   xxx ctermfg=67 guifg=#5d87bf
    DevIconHaml                            { fg="#eaeae1", }, -- DevIconHaml    xxx ctermfg=255 guifg=#eaeae1
    DevIconAlmalinux                       { fg="#000000", }, -- DevIconAlmalinux xxx ctermfg=16 guifg=#000000
    DevIconEx                              { fg="#a074c4", }, -- DevIconEx      xxx ctermfg=140 guifg=#a074c4
    DevIconGentoo                          { fg="#b1abce", }, -- DevIconGentoo  xxx ctermfg=146 guifg=#b1abce
    DevIconNix                             { fg="#7ebae4", }, -- DevIconNix     xxx ctermfg=110 guifg=#7ebae4
    DevIconParrot                          { fg="#000000", }, -- DevIconParrot  xxx ctermfg=16 guifg=#000000
    DevIconCMake                           { fg="#6d8086", }, -- DevIconCMake   xxx ctermfg=66 guifg=#6d8086
    DevIconSh                              { fg="#4d5a5e", }, -- DevIconSh      xxx ctermfg=240 guifg=#4d5a5e
    DevIconPl                              { fg="#519aba", }, -- DevIconPl      xxx ctermfg=74 guifg=#519aba
    DevIconPsScriptModulefile              { fg="#6975c4", }, -- DevIconPsScriptModulefile xxx ctermfg=68 guifg=#6975c4
    DevIconProlog                          { fg="#e4b854", }, -- DevIconProlog  xxx ctermfg=179 guifg=#e4b854
    DevIconPxi                             { fg="#5aa7e4", }, -- DevIconPxi     xxx ctermfg=39 guifg=#5aa7e4
    DevIconPrisma                          { fg="#ffffff", }, -- DevIconPrisma  xxx ctermfg=231 guifg=#ffffff
    DevIconHpp                             { fg="#a074c4", }, -- DevIconHpp     xxx ctermfg=140 guifg=#a074c4
    DevIconPpt                             { fg="#cb4a32", }, -- DevIconPpt     xxx ctermfg=160 guifg=#cb4a32
    DevIconHbs                             { fg="#f0772b", }, -- DevIconHbs     xxx ctermfg=202 guifg=#f0772b
  }
end)
return theme
