-- autogenerated lush spec on Sunday 14 January 2024 01:42:55 AM
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    Normal                                 { bg=hsl("#000000"), fg=hsl("#bcbcbc"), }, -- Normal         xxx ctermfg=250 ctermbg=16 guifg=#bcbcbc guibg=#000000
    Visual                                 { bg=hsl("#000000"), gui="reverse", fg=hsl("#bcbcbc"), }, -- Visual         xxx cterm=reverse ctermfg=250 ctermbg=16 gui=reverse guifg=#bcbcbc guibg=#000000
    SpecialKey                             { bg=hsl("#eeeeee"), fg=hsl("#000000"), }, -- SpecialKey     xxx ctermfg=16 ctermbg=255 guifg=#000000 guibg=#eeeeee
    iCursor                                { SpecialKey }, -- iCursor        xxx links to SpecialKey
    TermCursor                             { gui="reverse", }, -- TermCursor     xxx cterm=reverse gui=reverse
    Comment                                { bg=hsl("#000000"), fg=hsl("#585858") }, -- Comment        xxx ctermfg=240 ctermbg=16 guifg=#585858 guibg=#000000
    NonText                                { Comment, gui="bold", fg=Comment.fg.darken(10) }, -- NonText        xxx ctermfg=12 gui=bold guifg=Blue
    EndOfBuffer                            { NonText }, -- EndOfBuffer    xxx links to NonText
    Whitespace                             { NonText }, -- Whitespace     xxx links to NonText
    GitSignsCurrentLineBlame               { NonText }, -- GitSignsCurrentLineBlame xxx links to NonText
    Directory                              { fg="cyan", }, -- Directory      xxx ctermfg=159 guifg=Cyan
    ErrorMsg                               { bg="#af0000", fg="#eeeeee", }, -- ErrorMsg       xxx ctermfg=255 ctermbg=124 guifg=#eeeeee guibg=#af0000
    NvimInvalidSpacing                     { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    Search                                 { bg = hsl(52, 52, 52), fg = hsl(52, 10, 10) }, -- Search         xxx ctermfg=245 ctermbg=236 guifg=#8a8a8a guibg=#303030
    IncSearch                              { bg=Search.bg.ro(-20), fg=Search.fg.da(90) }, -- IncSearch      xxx cterm=reverse ctermfg=255 ctermbg=245 gui=reverse guifg=#eeeeee guibg=#8a8a8a
    CurSearch                              { bg=Search.bg.ro(-40), fg=Search.fg.da(90) }, -- CurSearch      xxx links to Search
    QuickFixLine                           { Search }, -- QuickFixLine   xxx links to Search
    Substitute                             { Search }, -- Substitute     xxx links to Search
    MoreMsg                                { gui="bold", fg="seagreen", }, -- MoreMsg        xxx ctermfg=121 gui=bold guifg=SeaGreen
    ModeMsg                                { gui="bold", }, -- ModeMsg        xxx cterm=bold gui=bold
    LineNr                                 { Comment, fg=Comment.fg.lighten(20) }, -- LineNr         xxx ctermfg=11 guifg=Yellow
    LineNrAbove                            { LineNr }, -- LineNrAbove    xxx links to LineNr
    LineNrBelow                            { LineNr }, -- LineNrBelow    xxx links to LineNr
    CursorLineNr                           { LineNr, gui="bold" }, -- CursorLineNr   xxx cterm=underline ctermfg=11 gui=bold guifg=Yellow
    Question                               { gui="bold", fg="green", }, -- Question       xxx ctermfg=121 gui=bold guifg=Green
    StatusLine                             { bg="#000000", gui="bold,reverse", fg="#8a8a8a", }, -- StatusLine     xxx cterm=bold,reverse ctermfg=245 ctermbg=16 gui=bold,reverse guifg=#8a8a8a guibg=#000000
    MsgSeparator                           { StatusLine }, -- MsgSeparator   xxx links to StatusLine
    StatusLineNC                           { bg="#000000", gui="reverse", fg="#303030", }, -- StatusLineNC   xxx cterm=reverse ctermfg=236 ctermbg=16 gui=reverse guifg=#303030 guibg=#000000
    Title                                  { gui="bold", fg="magenta", }, -- Title          xxx ctermfg=225 gui=bold guifg=Magenta
    FloatTitle                             { Title }, -- FloatTitle     xxx links to Title
    VertSplit                              { Visual }, -- VertSplit      xxx links to Visual
    UfoPreviewCursorLine                   { Visual }, -- UfoPreviewCursorLine xxx links to Visual
    VisualNOS                              { Visual }, -- VisualNOS      xxx links to Visual
    TelescopeSelection                     { Visual }, -- TelescopeSelection xxx links to Visual
    WarningMsg                             { fg="red", }, -- WarningMsg     xxx ctermfg=224 guifg=Red
    WildMenu                               { bg="#eeeeee", fg="#585858", }, -- WildMenu       xxx ctermfg=240 ctermbg=255 guifg=#585858 guibg=#eeeeee
    Folded                                 { bg="darkgrey", fg="cyan", }, -- Folded         xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=DarkGrey
    FoldColumn                             { bg="grey", fg="cyan", }, -- FoldColumn     xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey
    CursorLineFold                         { FoldColumn }, -- CursorLineFold xxx links to FoldColumn
    DiffAdd                                { bg="darkblue", }, -- DiffAdd        xxx ctermbg=4 guibg=DarkBlue
    GitSignsAddPreview                     { DiffAdd }, -- GitSignsAddPreview xxx links to DiffAdd
    DiffChange                             { bg="#eeeeee", fg="#d70000", }, -- DiffChange     xxx ctermfg=160 ctermbg=255 guifg=#d70000 guibg=#eeeeee
    diffChanged                            { DiffChange }, -- diffChanged    xxx links to DiffChange
    DiffDelete                             { bg="darkcyan", gui="bold", fg="blue", }, -- DiffDelete     xxx ctermfg=12 ctermbg=6 gui=bold guifg=Blue guibg=DarkCyan
    GitSignsDeletePreview                  { DiffDelete }, -- GitSignsDeletePreview xxx links to DiffDelete
    DiffText                               { bg="#ff0000", gui="bold", fg="#bcbcbc", }, -- DiffText       xxx cterm=bold ctermfg=250 ctermbg=196 gui=bold guifg=#bcbcbc guibg=#ff0000
    SignColumn                             { bg="#585858", fg="#af0000", }, -- SignColumn     xxx ctermfg=124 ctermbg=240 guifg=#af0000 guibg=#585858
    CursorLineSign                         { SignColumn }, -- CursorLineSign xxx links to SignColumn
    Conceal                                { bg="darkgrey", fg="lightgrey", }, -- Conceal        xxx ctermfg=7 ctermbg=242 guifg=LightGrey guibg=DarkGrey
    SpellBad                               { fg="#eeeeee", bg="#870000", gui="undercurl", sp="red", }, -- SpellBad       xxx cterm=undercurl ctermfg=255 ctermbg=88 gui=undercurl guifg=#eeeeee guibg=#870000 guisp=Red
    SpellCap                               { bg="#af0000", fg="#eeeeee", sp="blue", }, -- SpellCap       xxx ctermfg=255 ctermbg=124 guifg=#eeeeee guibg=#af0000 guisp=Blue
    SpellRare                              { bg="#000000", fg="#af0000", sp="magenta", }, -- SpellRare      xxx ctermfg=124 ctermbg=16 guifg=#af0000 guibg=#000000 guisp=Magenta
    rstEmphasis                            { SpellRare }, -- rstEmphasis    xxx links to SpellRare
    SpellLocal                             { gui="undercurl", sp="cyan", }, -- SpellLocal     xxx ctermbg=14 gui=undercurl guisp=Cyan
    Pmenu                                  { bg="#585858", fg="#eeeeee", }, -- Pmenu          xxx ctermfg=255 ctermbg=240 guifg=#eeeeee guibg=#585858
    PmenuKind                              { Pmenu }, -- PmenuKind      xxx links to Pmenu
    PmenuExtra                             { Pmenu }, -- PmenuExtra     xxx links to Pmenu
    NormalFloat                            { Pmenu }, -- NormalFloat    xxx links to Pmenu
    PmenuSel                               { bg="darkgrey", }, -- PmenuSel       xxx ctermfg=242 ctermbg=0 guibg=DarkGrey
    PmenuKindSel                           { PmenuSel }, -- PmenuKindSel   xxx links to PmenuSel
    PmenuExtraSel                          { PmenuSel }, -- PmenuExtraSel  xxx links to PmenuSel
    PmenuSbar                              { bg="grey", }, -- PmenuSbar      xxx ctermbg=248 guibg=Grey
    UfoPreviewSbar                         { PmenuSbar }, -- UfoPreviewSbar xxx links to PmenuSbar
    PmenuThumb                             { bg="#585858", fg="#080808", }, -- PmenuThumb     xxx ctermfg=232 ctermbg=240 guifg=#080808 guibg=#585858
    UfoPreviewThumb                        { PmenuThumb }, -- UfoPreviewThumb xxx links to PmenuThumb
    TabLine                                { bg="darkgrey", gui="underline", }, -- TabLine        xxx cterm=underline ctermfg=15 ctermbg=242 gui=underline guibg=DarkGrey
    TabLineSel                             { gui="bold", }, -- TabLineSel     xxx cterm=bold gui=bold
    TabLineFill                            { gui="reverse", }, -- TabLineFill    xxx cterm=reverse gui=reverse
    CursorColumn                           { bg="grey40", }, -- CursorColumn   xxx ctermbg=242 guibg=Grey40
    CursorLine                             { bg="#121212", }, -- CursorLine     xxx ctermbg=233 guibg=#121212
    ColorColumn                            { bg="darkred", }, -- ColorColumn    xxx ctermbg=1 guibg=DarkRed
    WinBar                                 { gui="bold", }, -- WinBar         xxx cterm=bold gui=bold
    WinBarNC                               { WinBar }, -- WinBarNC       xxx links to WinBar
    Cursor                                 { bg="fg", fg="bg", }, -- Cursor         xxx guifg=bg guibg=fg
    lCursor                                { bg="fg", fg="bg", }, -- lCursor        xxx guifg=bg guibg=fg
    Boolean                                { Normal }, -- Boolean        xxx links to Normal
    Exception                              { Normal }, -- Exception      xxx links to Normal
    Macro                                  { Normal }, -- Macro          xxx links to Normal
    Delimiter                              { Normal }, -- Delimiter      xxx links to Normal
    Debug                                  { Normal }, -- Debug          xxx links to Normal
    NvimSpacing                            { Normal }, -- NvimSpacing    xxx links to Normal
    NotifyTRACEBody                        { Normal }, -- NotifyTRACEBody xxx links to Normal
    NotifyDEBUGBody                        { Normal }, -- NotifyDEBUGBody xxx links to Normal
    NotifyINFOBody                         { Normal }, -- NotifyINFOBody xxx links to Normal
    NotifyERRORBody                        { Normal }, -- NotifyERRORBody xxx links to Normal
    DapUIFrameName                         { Normal }, -- DapUIFrameName xxx links to Normal
    DapUINormal                            { Normal }, -- DapUINormal    xxx links to Normal
    NotifyBackground                       { Normal }, -- NotifyBackground xxx links to Normal
    DapUIValue                             { Normal }, -- DapUIValue     xxx links to Normal
    DapUIVariable                          { Normal }, -- DapUIVariable  xxx links to Normal
    NotifyWARNBody                         { Normal }, -- NotifyWARNBody xxx links to Normal
    FloatShadow                            { blend=80, bg="black", }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough                     { blend=100, bg="black", }, -- FloatShadowThrough xxx guibg=Black blend=100
    RedrawDebugNormal                      { gui="reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    RedrawDebugClear                       { bg="yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed                    { bg="green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugRecompose                   { bg="red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Error                                  { bg="#870000", fg="#eeeeee", }, -- Error          xxx ctermfg=255 ctermbg=88 guifg=#eeeeee guibg=#870000
    NvimInvalid                            { Error }, -- NvimInvalid    xxx links to Error
    cError                                 { Error }, -- cError         xxx links to Error
    cBadContinuation                       { Error }, -- cBadContinuation xxx links to Error
    Todo                                   { bg="yellow", fg="blue", }, -- Todo           xxx ctermfg=0 ctermbg=11 guifg=Blue guibg=Yellow
    cTodo                                  { Todo }, -- cTodo          xxx links to Todo
    String                                 { bg="#000000", fg="#8a8a8a", }, -- String         xxx ctermfg=245 ctermbg=16 guifg=#8a8a8a guibg=#000000
    SpecialComment                         { String }, -- SpecialComment xxx links to String
    sym"@string"                           { String }, -- @string        xxx links to String
    NvimString                             { String }, -- NvimString     xxx links to String
    cString                                { String }, -- cString        xxx links to String
    cppRawString                           { String }, -- cppRawString   xxx links to String
    cppString                              { String }, -- cppString      xxx links to String
    Constant                               { bg="#000000", fg="#d0d0d0", }, -- Constant       xxx ctermfg=252 ctermbg=16 guifg=#d0d0d0 guibg=#000000
    sym"@constant"                         { Constant }, -- @constant      xxx links to Constant
    sym"@lsp.type.enumMember"              { Constant }, -- @lsp.type.enumMember xxx links to Constant
    cppConstant                            { Constant }, -- cppConstant    xxx links to Constant
    cConstant                              { Constant }, -- cConstant      xxx links to Constant
    AerialConstantIcon                     { Constant }, -- AerialConstantIcon xxx links to Constant
    Number                                 { bg="#000000", fg="#ff0000", }, -- Number         xxx ctermfg=196 ctermbg=16 guifg=#ff0000 guibg=#000000
    Character                              { Number }, -- Character      xxx links to Number
    Float                                  { Number }, -- Float          xxx links to Number
    Tag                                    { Number }, -- Tag            xxx links to Number
    sym"@number"                           { Number }, -- @number        xxx links to Number
    NvimNumber                             { Number }, -- NvimNumber     xxx links to Number
    cppFloat                               { Number }, -- cppFloat       xxx links to Number
    cppNumber                              { Number }, -- cppNumber      xxx links to Number
    cOctal                                 { Number }, -- cOctal         xxx links to Number
    cNumber                                { Number }, -- cNumber        xxx links to Number
    Identifier                             { fg="#ffffff", gui="bold" }, -- Identifier     xxx cterm=bold ctermfg=14 guifg=#40ffff
    sym"@text.reference"                   { Identifier }, -- @text.reference xxx links to Identifier
    sym"@parameter"                        { Identifier }, -- @parameter     xxx links to Identifier
    sym"@field"                            { Identifier }, -- @field         xxx links to Identifier
    sym"@property"                         { Identifier }, -- @property      xxx links to Identifier
    sym"@variable"                         { Identifier }, -- @variable      xxx links to Identifier
    sym"@namespace"                        { Identifier }, -- @namespace     xxx links to Identifier
    sym"@lsp.type.parameter"               { Identifier }, -- @lsp.type.parameter xxx links to Identifier
    sym"@lsp.type.property"                { Identifier }, -- @lsp.type.property xxx links to Identifier
    NvimIdentifier                         { Identifier }, -- NvimIdentifier xxx links to Identifier
    AerialArrayIcon                        { Identifier }, -- AerialArrayIcon xxx links to Identifier
    AerialBooleanIcon                      { Identifier }, -- AerialBooleanIcon xxx links to Identifier
    AerialEnumMemberIcon                   { Identifier }, -- AerialEnumMemberIcon xxx links to Identifier
    AerialEventIcon                        { Identifier }, -- AerialEventIcon xxx links to Identifier
    AerialFieldIcon                        { Identifier }, -- AerialFieldIcon xxx links to Identifier
    AerialFileIcon                         { Identifier }, -- AerialFileIcon xxx links to Identifier
    AerialKeyIcon                          { Identifier }, -- AerialKeyIcon  xxx links to Identifier
    AerialNullIcon                         { Identifier }, -- AerialNullIcon xxx links to Identifier
    AerialNumberIcon                       { Identifier }, -- AerialNumberIcon xxx links to Identifier
    AerialObjectIcon                       { Identifier }, -- AerialObjectIcon xxx links to Identifier
    AerialOperatorIcon                     { Identifier }, -- AerialOperatorIcon xxx links to Identifier
    AerialPropertyIcon                     { Identifier }, -- AerialPropertyIcon xxx links to Identifier
    AerialStringIcon                       { Identifier }, -- AerialStringIcon xxx links to Identifier
    AerialTypeParameterIcon                { Identifier }, -- AerialTypeParameterIcon xxx links to Identifier
    AerialVariableIcon                     { Identifier }, -- AerialVariableIcon xxx links to Identifier
    WhichKeyDesc                           { Identifier }, -- WhichKeyDesc   xxx links to Identifier
    Statement                              { gui="bold", fg="#ffff60", }, -- Statement      xxx ctermfg=11 gui=bold guifg=#ffff60
    cppStatement                           { Statement }, -- cppStatement   xxx links to Statement
    cStatement                             { Statement }, -- cStatement     xxx links to Statement
    Keyword                                { bg="#000000", fg="#eeeeee", }, -- Keyword        xxx ctermfg=255 ctermbg=16 guifg=#eeeeee guibg=#000000
    Function                               { Keyword }, -- Function       xxx links to Keyword
    Conditional                            { Keyword }, -- Conditional    xxx links to Keyword
    Repeat                                 { Keyword }, -- Repeat         xxx links to Keyword
    Label                                  { Keyword }, -- Label          xxx links to Keyword
    Operator                               { Keyword }, -- Operator       xxx links to Keyword
    Include                                { Keyword }, -- Include        xxx links to Keyword
    Define                                 { Keyword }, -- Define         xxx links to Keyword
    PreCondit                              { Keyword }, -- PreCondit      xxx links to Keyword
    StorageClass                           { Keyword }, -- StorageClass   xxx links to Keyword
    Structure                              { Keyword }, -- Structure      xxx links to Keyword
    Typedef                                { Keyword }, -- Typedef        xxx links to Keyword
    SpecialChar                            { Keyword }, -- SpecialChar    xxx links to Keyword
    sym"@keyword"                          { Keyword }, -- @keyword       xxx links to Keyword
    diffCommon                             { Keyword }, -- diffCommon     xxx links to Keyword
    diffAdded                              { Keyword }, -- diffAdded      xxx links to Keyword
    WhichKeyGroup                          { Keyword }, -- WhichKeyGroup  xxx links to Keyword
    PreProc                                { fg="#ff80ff", }, -- PreProc        xxx ctermfg=81 guifg=#ff80ff
    sym"@preproc"                          { PreProc }, -- @preproc       xxx links to PreProc
    cPreProc                               { PreProc }, -- cPreProc       xxx links to PreProc
    cOctalZero                             { PreProc }, -- cOctalZero     xxx links to PreProc
    Type                                   { gui="bold", fg="#60ff60", }, -- Type           xxx ctermfg=121 gui=bold guifg=#60ff60
    sym"@type"                             { Type }, -- @type          xxx links to Type
    NvimNumberPrefix                       { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOptionSigil                        { Type }, -- NvimOptionSigil xxx links to Type
    cppType                                { Type }, -- cppType        xxx links to Type
    cppModifier                            { Type }, -- cppModifier    xxx links to Type
    cType                                  { Type }, -- cType          xxx links to Type
    AerialClassIcon                        { Type }, -- AerialClassIcon xxx links to Type
    AerialEnumIcon                         { Type }, -- AerialEnumIcon xxx links to Type
    AerialInterfaceIcon                    { Type }, -- AerialInterfaceIcon xxx links to Type
    AerialStructIcon                       { Type }, -- AerialStructIcon xxx links to Type
    Special                                { fg="orange", }, -- Special        xxx ctermfg=224 guifg=Orange
    sym"@constructor"                      { Special }, -- @constructor   xxx links to Special
    NotifyLogTitle                         { Special }, -- NotifyLogTitle xxx links to Special
    TelescopeMatching                      { Special }, -- TelescopeMatching xxx links to Special
    AerialConstructorIcon                  { Special }, -- AerialConstructorIcon xxx links to Special
    DiagnosticError                        { fg="red", }, -- DiagnosticError xxx ctermfg=1 guifg=Red
    DiagnosticVirtualTextError             { DiagnosticError }, -- DiagnosticVirtualTextError xxx links to DiagnosticError
    DiagnosticFloatingError                { DiagnosticError }, -- DiagnosticFloatingError xxx links to DiagnosticError
    DiagnosticSignError                    { DiagnosticError }, -- DiagnosticSignError xxx links to DiagnosticError
    DiagnosticWarn                         { fg="orange", }, -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
    DiagnosticVirtualTextWarn              { DiagnosticWarn }, -- DiagnosticVirtualTextWarn xxx links to DiagnosticWarn
    DiagnosticFloatingWarn                 { DiagnosticWarn }, -- DiagnosticFloatingWarn xxx links to DiagnosticWarn
    DiagnosticSignWarn                     { DiagnosticWarn }, -- DiagnosticSignWarn xxx links to DiagnosticWarn
    DiagnosticInfo                         { fg="lightblue", }, -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
    DiagnosticVirtualTextInfo              { DiagnosticInfo }, -- DiagnosticVirtualTextInfo xxx links to DiagnosticInfo
    DiagnosticFloatingInfo                 { DiagnosticInfo }, -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
    DiagnosticSignInfo                     { DiagnosticInfo }, -- DiagnosticSignInfo xxx links to DiagnosticInfo
    DiagnosticHint                         { fg="lightgrey", }, -- DiagnosticHint xxx ctermfg=7 guifg=LightGrey
    DiagnosticVirtualTextHint              { DiagnosticHint }, -- DiagnosticVirtualTextHint xxx links to DiagnosticHint
    DiagnosticFloatingHint                 { DiagnosticHint }, -- DiagnosticFloatingHint xxx links to DiagnosticHint
    DiagnosticSignHint                     { DiagnosticHint }, -- DiagnosticSignHint xxx links to DiagnosticHint
    DiagnosticOk                           { fg="lightgreen", }, -- DiagnosticOk   xxx ctermfg=10 guifg=LightGreen
    DiagnosticVirtualTextOk                { DiagnosticOk }, -- DiagnosticVirtualTextOk xxx links to DiagnosticOk
    DiagnosticFloatingOk                   { DiagnosticOk }, -- DiagnosticFloatingOk xxx links to DiagnosticOk
    DiagnosticSignOk                       { DiagnosticOk }, -- DiagnosticSignOk xxx links to DiagnosticOk
    DiagnosticUnderlineError               { gui="underline", sp="red", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
    DiagnosticUnderlineWarn                { gui="underline", sp="orange", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
    DiagnosticUnderlineInfo                { gui="underline", sp="lightblue", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
    DiagnosticUnderlineHint                { gui="underline", sp="lightgrey", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
    DiagnosticUnderlineOk                  { gui="underline", sp="lightgreen", }, -- DiagnosticUnderlineOk xxx cterm=underline gui=underline guisp=LightGreen
    DiagnosticDeprecated                   { gui="strikethrough", sp="red", }, -- DiagnosticDeprecated xxx cterm=strikethrough gui=strikethrough guisp=Red
    DiagnosticUnnecessary                  { Comment }, -- DiagnosticUnnecessary xxx links to Comment
    sym"@comment"                          { Comment }, -- @comment       xxx links to Comment
    sym"@lsp.type.comment"                 { Comment }, -- @lsp.type.comment xxx links to Comment
    cCppOut                                { Comment }, -- cCppOut        xxx links to Comment
    cComment                               { Comment }, -- cComment       xxx links to Comment
    CopilotAnnotation                      { Comment }, -- CopilotAnnotation xxx links to Comment
    CopilotSuggestion                      { Comment }, -- CopilotSuggestion xxx links to Comment
    UfoFoldedEllipsis                      { Comment }, -- UfoFoldedEllipsis xxx links to Comment
    diffRemoved                            { Comment }, -- diffRemoved    xxx links to Comment
    NotifyLogTime                          { Comment }, -- NotifyLogTime  xxx links to Comment
    WhichKeySeparator                      { Comment }, -- WhichKeySeparator xxx links to Comment
    WhichKeyValue                          { Comment }, -- WhichKeyValue  xxx links to Comment
    Underlined                             { gui="underline", fg="#80a0ff", }, -- Underlined     xxx cterm=underline ctermfg=81 gui=underline guifg=#80a0ff
    sym"@text.underline"                   { Underlined }, -- @text.underline xxx links to Underlined
    MatchParen                             { bg="#585858", fg="#000000", }, -- MatchParen     xxx ctermfg=16 ctermbg=240 guifg=#000000 guibg=#585858
    Ignore                                 { fg="bg", }, -- Ignore         xxx ctermfg=0 guifg=bg
    NvimInternalError                      { bg="red", fg="red", }, -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
    NvimFigureBrace                        { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimSingleQuotedUnknownEscape          { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSingleQuotedUnknownEscape   { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
    DevIconSh                              { fg="#4d5a5e", }, -- DevIconSh      xxx ctermfg=240 guifg=#4d5a5e
    DevIconZshrc                           { fg="#89e051", }, -- DevIconZshrc   xxx ctermfg=113 guifg=#89e051
    DevIconTxt                             { fg="#89e051", }, -- DevIconTxt     xxx ctermfg=113 guifg=#89e051
    DevIconCson                            { fg="#cbcb41", }, -- DevIconCson    xxx ctermfg=185 guifg=#cbcb41
    DevIconAac                             { fg="#66d8ef", }, -- DevIconAac     xxx ctermfg=45 guifg=#66d8ef
    DevIconScheme                          { fg="#eeeeee", }, -- DevIconScheme  xxx ctermfg=255 guifg=#eeeeee
    DevIconDebian                          { fg="#a80030", }, -- DevIconDebian  xxx ctermfg=88 guifg=#a80030
    DevIconTs                              { fg="#519aba", }, -- DevIconTs      xxx ctermfg=74 guifg=#519aba
    DevIconPackedResource                  { fg="#6d8086", }, -- DevIconPackedResource xxx ctermfg=66 guifg=#6d8086
    DevIconRb                              { fg="#701516", }, -- DevIconRb      xxx ctermfg=52 guifg=#701516
    DevIconDeepin                          { fg="#2ca7f8", }, -- DevIconDeepin  xxx ctermfg=39 guifg=#2ca7f8
    DevIconBazelBuild                      { fg="#89e051", }, -- DevIconBazelBuild xxx ctermfg=113 guifg=#89e051
    DevIconRakefile                        { fg="#701516", }, -- DevIconRakefile xxx ctermfg=52 guifg=#701516
    DevIconPp                              { fg="#ffa61a", }, -- DevIconPp      xxx ctermfg=214 guifg=#ffa61a
    DevIconProlog                          { fg="#e4b854", }, -- DevIconProlog  xxx ctermfg=179 guifg=#e4b854
    DevIconDevuan                          { fg="#404a52", }, -- DevIconDevuan  xxx ctermfg=238 guifg=#404a52
    DevIconPpt                             { fg="#cb4a32", }, -- DevIconPpt     xxx ctermfg=160 guifg=#cb4a32
    DevIconElm                             { fg="#519aba", }, -- DevIconElm     xxx ctermfg=74 guifg=#519aba
    DevIconHeex                            { fg="#a074c4", }, -- DevIconHeex    xxx ctermfg=140 guifg=#a074c4
    DevIconElementary                      { fg="#5890c2", }, -- DevIconElementary xxx ctermfg=67 guifg=#5890c2
    DevIconPng                             { fg="#a074c4", }, -- DevIconPng     xxx ctermfg=140 guifg=#a074c4
    DevIconTFVars                          { fg="#5f43e9", }, -- DevIconTFVars  xxx ctermfg=93 guifg=#5f43e9
    DevIconPsd                             { fg="#519aba", }, -- DevIconPsd     xxx ctermfg=74 guifg=#519aba
    DevIconBazelWorkspace                  { fg="#89e051", }, -- DevIconBazelWorkspace xxx ctermfg=113 guifg=#89e051
    DevIconEndeavour                       { fg="#7b3db9", }, -- DevIconEndeavour xxx ctermfg=91 guifg=#7b3db9
    DevIconPdf                             { fg="#b30b00", }, -- DevIconPdf     xxx ctermfg=124 guifg=#b30b00
    DevIconHbs                             { fg="#f0772b", }, -- DevIconHbs     xxx ctermfg=202 guifg=#f0772b
    DevIconPsManifestfile                  { fg="#6975c4", }, -- DevIconPsManifestfile xxx ctermfg=68 guifg=#6975c4
    DevIconFedora                          { fg="#072a5e", }, -- DevIconFedora  xxx ctermfg=17 guifg=#072a5e
    DevIconFennel                          { fg="#fff3d7", }, -- DevIconFennel  xxx ctermfg=230 guifg=#fff3d7
    DevIconSettingsJson                    { fg="#854cc7", }, -- DevIconSettingsJson xxx ctermfg=98 guifg=#854cc7
    DevIconFreeBSD                         { fg="#c90f02", }, -- DevIconFreeBSD xxx ctermfg=160 guifg=#c90f02
    DevIconDrools                          { fg="#ffafaf", }, -- DevIconDrools  xxx ctermfg=217 guifg=#ffafaf
    DevIconSystemVerilog                   { fg="#019833", }, -- DevIconSystemVerilog xxx ctermfg=28 guifg=#019833
    DevIconSwift                           { fg="#e37933", }, -- DevIconSwift   xxx ctermfg=166 guifg=#e37933
    DevIconSvelte                          { fg="#ff3e00", }, -- DevIconSvelte  xxx ctermfg=196 guifg=#ff3e00
    DevIconIni                             { fg="#6d8086", }, -- DevIconIni     xxx ctermfg=66 guifg=#6d8086
    DevIconParrot                          { fg="#000000", }, -- DevIconParrot  xxx ctermfg=16 guifg=#000000
    DevIconApple                           { fg="#a2aaad", }, -- DevIconApple   xxx ctermfg=248 guifg=#a2aaad
    DevIconReScript                        { fg="#cc3e44", }, -- DevIconReScript xxx ctermfg=167 guifg=#cc3e44
    DevIconBrewfile                        { fg="#701516", }, -- DevIconBrewfile xxx ctermfg=52 guifg=#701516
    DevIconWebm                            { fg="#fd971f", }, -- DevIconWebm    xxx ctermfg=208 guifg=#fd971f
    DevIconWebp                            { fg="#a074c4", }, -- DevIconWebp    xxx ctermfg=140 guifg=#a074c4
    DevIconRake                            { fg="#701516", }, -- DevIconRake    xxx ctermfg=52 guifg=#701516
    DevIconXml                             { fg="#e37933", }, -- DevIconXml     xxx ctermfg=166 guifg=#e37933
    DevIconCMake                           { fg="#6d8086", }, -- DevIconCMake   xxx ctermfg=66 guifg=#6d8086
    DevIconBabelrc                         { fg="#cbcb41", }, -- DevIconBabelrc xxx ctermfg=185 guifg=#cbcb41
    DevIconEpp                             { fg="#ffa61a", }, -- DevIconEpp     xxx ctermfg=214 guifg=#ffa61a
    DevIconEslintrc                        { fg="#4b32c3", }, -- DevIconEslintrc xxx ctermfg=56 guifg=#4b32c3
    DevIconManjaro                         { fg="#33b959", }, -- DevIconManjaro xxx ctermfg=35 guifg=#33b959
    DevIconDart                            { fg="#03589c", }, -- DevIconDart    xxx ctermfg=25 guifg=#03589c
    DevIconJava                            { fg="#cc3e44", }, -- DevIconJava    xxx ctermfg=167 guifg=#cc3e44
    DevIconAppleScript                     { fg="#6d8085", }, -- DevIconAppleScript xxx ctermfg=66 guifg=#6d8085
    DevIconConf                            { fg="#6d8086", }, -- DevIconConf    xxx ctermfg=66 guifg=#6d8086
    DevIconVim                             { fg="#019833", }, -- DevIconVim     xxx ctermfg=28 guifg=#019833
    DevIconToml                            { fg="#ffffff", }, -- DevIconToml    xxx ctermfg=231 guifg=#ffffff
    DevIconMageia                          { fg="#2397d4", }, -- DevIconMageia  xxx ctermfg=67 guifg=#2397d4
    DevIconLiquid                          { fg="#95bf47", }, -- DevIconLiquid  xxx ctermfg=106 guifg=#95bf47
    DevIconFsi                             { fg="#519aba", }, -- DevIconFsi     xxx ctermfg=74 guifg=#519aba
    DevIconFsx                             { fg="#519aba", }, -- DevIconFsx     xxx ctermfg=74 guifg=#519aba
    DevIconTextScene                       { fg="#a074c4", }, -- DevIconTextScene xxx ctermfg=140 guifg=#a074c4
    DevIconLuau                            { fg="#00a2ff", }, -- DevIconLuau    xxx ctermfg=75 guifg=#00a2ff
    DevIconGDScript                        { fg="#6d8086", }, -- DevIconGDScript xxx ctermfg=66 guifg=#6d8086
    DevIconMotoko                          { fg="#9772fb", }, -- DevIconMotoko  xxx ctermfg=135 guifg=#9772fb
    DevIconBat                             { fg="#c1f12e", }, -- DevIconBat     xxx ctermfg=191 guifg=#c1f12e
    DevIconSvg                             { fg="#ffb13b", }, -- DevIconSvg     xxx ctermfg=214 guifg=#ffb13b
    DevIconAwk                             { fg="#4d5a5e", }, -- DevIconAwk     xxx ctermfg=240 guifg=#4d5a5e
    DevIconOpenTypeFont                    { fg="#ececec", }, -- DevIconOpenTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconMakefile                        { fg="#6d8086", }, -- DevIconMakefile xxx ctermfg=66 guifg=#6d8086
    DevIconScss                            { fg="#f55385", }, -- DevIconScss    xxx ctermfg=204 guifg=#f55385
    DevIconVHDL                            { fg="#019833", }, -- DevIconVHDL    xxx ctermfg=28 guifg=#019833
    DevIconGraphQL                         { fg="#e535ab", }, -- DevIconGraphQL xxx ctermfg=199 guifg=#e535ab
    DevIconOrgMode                         { fg="#77aa99", }, -- DevIconOrgMode xxx ctermfg=73 guifg=#77aa99
    DevIconAi                              { fg="#cbcb41", }, -- DevIconAi      xxx ctermfg=185 guifg=#cbcb41
    DevIconHuff                            { fg="#4242c7", }, -- DevIconHuff    xxx ctermfg=56 guifg=#4242c7
    DevIconErl                             { fg="#b83998", }, -- DevIconErl     xxx ctermfg=163 guifg=#b83998
    DevIconHrl                             { fg="#b83998", }, -- DevIconHrl     xxx ctermfg=163 guifg=#b83998
    DevIconD                               { fg="#427819", }, -- DevIconD       xxx ctermfg=28 guifg=#427819
    DevIconErb                             { fg="#701516", }, -- DevIconErb     xxx ctermfg=52 guifg=#701516
    DevIconHaml                            { fg="#eaeae1", }, -- DevIconHaml    xxx ctermfg=255 guifg=#eaeae1
    DevIconPsScriptModulefile              { fg="#6975c4", }, -- DevIconPsScriptModulefile xxx ctermfg=68 guifg=#6975c4
    DevIconPsScriptfile                    { fg="#4273ca", }, -- DevIconPsScriptfile xxx ctermfg=68 guifg=#4273ca
    DevIconTSConfig                        { fg="#519aba", }, -- DevIconTSConfig xxx ctermfg=74 guifg=#519aba
    DevIconLinux                           { fg="#000000", }, -- DevIconLinux   xxx ctermfg=16 guifg=#000000
    DevIconPxd                             { fg="#5aa7e4", }, -- DevIconPxd     xxx ctermfg=39 guifg=#5aa7e4
    DevIconHs                              { fg="#a074c4", }, -- DevIconHs      xxx ctermfg=140 guifg=#a074c4
    DevIconPy                              { fg="#ffbc03", }, -- DevIconPy      xxx ctermfg=214 guifg=#ffbc03
    DevIconPyi                             { fg="#ffbc03", }, -- DevIconPyi     xxx ctermfg=214 guifg=#ffbc03
    DevIconPxi                             { fg="#5aa7e4", }, -- DevIconPxi     xxx ctermfg=39 guifg=#5aa7e4
    DevIconArch                            { fg="#0f94d2", }, -- DevIconArch    xxx ctermfg=67 guifg=#0f94d2
    DevIconHtm                             { fg="#e34c26", }, -- DevIconHtm     xxx ctermfg=196 guifg=#e34c26
    DevIconNPMrc                           { fg="#e8274b", }, -- DevIconNPMrc   xxx ctermfg=197 guifg=#e8274b
    DevIconR                               { fg="#2266ba", }, -- DevIconR       xxx ctermfg=25 guifg=#2266ba
    DevIconNim                             { fg="#f3d400", }, -- DevIconNim     xxx ctermfg=220 guifg=#f3d400
    DevIconEditorConfig                    { fg="#ffffff", }, -- DevIconEditorConfig xxx ctermfg=231 guifg=#ffffff
    DevIconNix                             { fg="#7ebae4", }, -- DevIconNix     xxx ctermfg=110 guifg=#7ebae4
    DevIconMixLock                         { fg="#a074c4", }, -- DevIconMixLock xxx ctermfg=140 guifg=#a074c4
    DevIconJsonc                           { fg="#cbcb41", }, -- DevIconJsonc   xxx ctermfg=185 guifg=#cbcb41
    DevIconEslintIgnore                    { fg="#4b32c3", }, -- DevIconEslintIgnore xxx ctermfg=56 guifg=#4b32c3
    DevIconYml                             { fg="#6d8086", }, -- DevIconYml     xxx ctermfg=66 guifg=#6d8086
    DevIconZshenv                          { fg="#89e051", }, -- DevIconZshenv  xxx ctermfg=113 guifg=#89e051
    DevIconZshprofile                      { fg="#89e051", }, -- DevIconZshprofile xxx ctermfg=113 guifg=#89e051
    DevIconMli                             { fg="#e37933", }, -- DevIconMli     xxx ctermfg=166 guifg=#e37933
    DevIconMl                              { fg="#e37933", }, -- DevIconMl      xxx ctermfg=166 guifg=#e37933
    DevIconDsStore                         { fg="#41535b", }, -- DevIconDsStore xxx ctermfg=239 guifg=#41535b
    DevIconBzl                             { fg="#89e051", }, -- DevIconBzl     xxx ctermfg=113 guifg=#89e051
    DevIconMjs                             { fg="#f1f134", }, -- DevIconMjs     xxx ctermfg=227 guifg=#f1f134
    DevIconJs                              { fg="#f1f134", }, -- DevIconJs      xxx ctermfg=227 guifg=#f1f134
    DevIconLog                             { fg="#ffffff", }, -- DevIconLog     xxx ctermfg=231 guifg=#ffffff
    DevIconCjs                             { fg="#f1f134", }, -- DevIconCjs     xxx ctermfg=227 guifg=#f1f134
    DevIconJsx                             { fg="#20c2e3", }, -- DevIconJsx     xxx ctermfg=45 guifg=#20c2e3
    DevIconH                               { fg="#a074c4", }, -- DevIconH       xxx ctermfg=140 guifg=#a074c4
    DevIconPackageJson                     { fg="#e8274b", }, -- DevIconPackageJson xxx ctermfg=197 guifg=#e8274b
    DevIconGitlabCI                        { fg="#e24329", }, -- DevIconGitlabCI xxx ctermfg=196 guifg=#e24329
    DevIconLuaurc                          { fg="#00a2ff", }, -- DevIconLuaurc  xxx ctermfg=75 guifg=#00a2ff
    DevIconRazorPage                       { fg="#512bd4", }, -- DevIconRazorPage xxx ctermfg=56 guifg=#512bd4
    DevIconWebmanifest                     { fg="#f1e05a", }, -- DevIconWebmanifest xxx ctermfg=185 guifg=#f1e05a
    DevIconCMakeLists                      { fg="#6d8086", }, -- DevIconCMakeLists xxx ctermfg=66 guifg=#6d8086
    DevIconPrisma                          { fg="#ffffff", }, -- DevIconPrisma  xxx ctermfg=231 guifg=#ffffff
    DevIconJl                              { fg="#a270ba", }, -- DevIconJl      xxx ctermfg=133 guifg=#a270ba
    DevIconKotlinScript                    { fg="#7f52ff", }, -- DevIconKotlinScript xxx ctermfg=99 guifg=#7f52ff
    DevIconKotlin                          { fg="#7f52ff", }, -- DevIconKotlin  xxx ctermfg=99 guifg=#7f52ff
    DevIconDump                            { fg="#dad8d8", }, -- DevIconDump    xxx ctermfg=188 guifg=#dad8d8
    DevIconDockerfile                      { fg="#458ee6", }, -- DevIconDockerfile xxx ctermfg=68 guifg=#458ee6
    DevIconGvimrc                          { fg="#019833", }, -- DevIconGvimrc  xxx ctermfg=28 guifg=#019833
    DevIconEmbeddedOpenTypeFont            { fg="#ececec", }, -- DevIconEmbeddedOpenTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconNPMIgnore                       { fg="#e8274b", }, -- DevIconNPMIgnore xxx ctermfg=197 guifg=#e8274b
    DevIconLess                            { fg="#563d7c", }, -- DevIconLess    xxx ctermfg=54 guifg=#563d7c
    DevIconExe                             { fg="#9f0500", }, -- DevIconExe     xxx ctermfg=124 guifg=#9f0500
    DevIconBibTeX                          { fg="#cbcb41", }, -- DevIconBibTeX  xxx ctermfg=185 guifg=#cbcb41
    DevIconSpecJs                          { fg="#cbcb41", }, -- DevIconSpecJs  xxx ctermfg=185 guifg=#cbcb41
    DevIconJavaScriptReactSpec             { fg="#20c2e3", }, -- DevIconJavaScriptReactSpec xxx ctermfg=45 guifg=#20c2e3
    DevIconSpecTs                          { fg="#519aba", }, -- DevIconSpecTs  xxx ctermfg=74 guifg=#519aba
    DevIconBazel                           { fg="#89e051", }, -- DevIconBazel   xxx ctermfg=113 guifg=#89e051
    DevIconTypeScriptReactSpec             { fg="#1354bf", }, -- DevIconTypeScriptReactSpec xxx ctermfg=26 guifg=#1354bf
    DevIconTcl                             { fg="#1e5cb3", }, -- DevIconTcl     xxx ctermfg=25 guifg=#1e5cb3
    DevIconTestJs                          { fg="#cbcb41", }, -- DevIconTestJs  xxx ctermfg=185 guifg=#cbcb41
    DevIconClojure                         { fg="#8dc149", }, -- DevIconClojure xxx ctermfg=113 guifg=#8dc149
    DevIconClojureC                        { fg="#8dc149", }, -- DevIconClojureC xxx ctermfg=113 guifg=#8dc149
    DevIconJavaScriptReactTest             { fg="#20c2e3", }, -- DevIconJavaScriptReactTest xxx ctermfg=45 guifg=#20c2e3
    DevIconClojureJS                       { fg="#519aba", }, -- DevIconClojureJS xxx ctermfg=74 guifg=#519aba
    DevIconTestTs                          { fg="#519aba", }, -- DevIconTestTs  xxx ctermfg=74 guifg=#519aba
    DevIconTypeScriptReactTest             { fg="#1354bf", }, -- DevIconTypeScriptReactTest xxx ctermfg=26 guifg=#1354bf
    DevIconCobol                           { fg="#005ca5", }, -- DevIconCobol   xxx ctermfg=25 guifg=#005ca5
    DevIconBash                            { fg="#89e051", }, -- DevIconBash    xxx ctermfg=113 guifg=#89e051
    DevIconCpp                             { fg="#519aba", }, -- DevIconCpp     xxx ctermfg=74 guifg=#519aba
    DevIconHtml                            { fg="#e44d26", }, -- DevIconHtml    xxx ctermfg=196 guifg=#e44d26
    DevIconRedhat                          { fg="#ee0000", }, -- DevIconRedhat  xxx ctermfg=196 guifg=#ee0000
    DevIconEx                              { fg="#a074c4", }, -- DevIconEx      xxx ctermfg=140 guifg=#a074c4
    DevIconSvelteConfig                    { fg="#ff3e00", }, -- DevIconSvelteConfig xxx ctermfg=196 guifg=#ff3e00
    DevIconCsh                             { fg="#4d5a5e", }, -- DevIconCsh     xxx ctermfg=240 guifg=#4d5a5e
    DevIconCentos                          { fg="#a2518d", }, -- DevIconCentos  xxx ctermfg=132 guifg=#a2518d
    DevIconEdn                             { fg="#519aba", }, -- DevIconEdn     xxx ctermfg=74 guifg=#519aba
    DevIconUbuntu                          { fg="#dd4814", }, -- DevIconUbuntu  xxx ctermfg=196 guifg=#dd4814
    DevIconArtix                           { fg="#41b4d7", }, -- DevIconArtix   xxx ctermfg=38 guifg=#41b4d7
    DevIconSlackware                       { fg="#475fa9", }, -- DevIconSlackware xxx ctermfg=61 guifg=#475fa9
    DevIconGo                              { fg="#519aba", }, -- DevIconGo      xxx ctermfg=74 guifg=#519aba
    DevIconSolus                           { fg="#4b5163", }, -- DevIconSolus   xxx ctermfg=239 guifg=#4b5163
    DevIconConfiguration                   { fg="#ececec", }, -- DevIconConfiguration xxx ctermfg=255 guifg=#ececec
    DevIconImportConfiguration             { fg="#ececec", }, -- DevIconImportConfiguration xxx ctermfg=255 guifg=#ececec
    DevIconCSharpProject                   { fg="#512bd4", }, -- DevIconCSharpProject xxx ctermfg=56 guifg=#512bd4
    DevIconAlmalinux                       { fg="#000000", }, -- DevIconAlmalinux xxx ctermfg=16 guifg=#000000
    DevIconSabayon                         { fg="#c6c6c6", }, -- DevIconSabayon xxx ctermfg=251 guifg=#c6c6c6
    DevIconTempl                           { fg="#dbbd30", }, -- DevIconTempl   xxx ctermfg=178 guifg=#dbbd30
    DevIconRss                             { fg="#fb9d3b", }, -- DevIconRss     xxx ctermfg=215 guifg=#fb9d3b
    DevIconRaspberryPiOS                   { fg="#be1848", }, -- DevIconRaspberryPiOS xxx ctermfg=161 guifg=#be1848
    DevIconXul                             { fg="#e37933", }, -- DevIconXul     xxx ctermfg=166 guifg=#e37933
    DevIconDesktopEntry                    { fg="#563d7c", }, -- DevIconDesktopEntry xxx ctermfg=54 guifg=#563d7c
    DevIconZorin                           { fg="#14a1e8", }, -- DevIconZorin   xxx ctermfg=39 guifg=#14a1e8
    DevIconScala                           { fg="#cc3e44", }, -- DevIconScala   xxx ctermfg=167 guifg=#cc3e44
    DevIconsbt                             { fg="#cc3e44", }, -- DevIconsbt     xxx ctermfg=167 guifg=#cc3e44
    DevIconCoffee                          { fg="#cbcb41", }, -- DevIconCoffee  xxx ctermfg=185 guifg=#cbcb41
    DevIconCp                              { fg="#519aba", }, -- DevIconCp      xxx ctermfg=74 guifg=#519aba
    DevIconJson                            { fg="#cbcb41", }, -- DevIconJson    xxx ctermfg=185 guifg=#cbcb41
    DevIconVerilog                         { fg="#019833", }, -- DevIconVerilog xxx ctermfg=28 guifg=#019833
    DevIconFavicon                         { fg="#cbcb41", }, -- DevIconFavicon xxx ctermfg=185 guifg=#cbcb41
    DevIconPm                              { fg="#519aba", }, -- DevIconPm      xxx ctermfg=74 guifg=#519aba
    DevIconRs                              { fg="#dea584", }, -- DevIconRs      xxx ctermfg=216 guifg=#dea584
    DevIconCxx                             { fg="#519aba", }, -- DevIconCxx     xxx ctermfg=74 guifg=#519aba
    DevIconGemspec                         { fg="#701516", }, -- DevIconGemspec xxx ctermfg=52 guifg=#701516
    DevIconPyx                             { fg="#5aa7e4", }, -- DevIconPyx     xxx ctermfg=39 guifg=#5aa7e4
    DevIconVue                             { fg="#8dc149", }, -- DevIconVue     xxx ctermfg=113 guifg=#8dc149
    DevIconTerminal                        { fg="#31b53e", }, -- DevIconTerminal xxx ctermfg=34 guifg=#31b53e
    DevIconFsharp                          { fg="#519aba", }, -- DevIconFsharp  xxx ctermfg=74 guifg=#519aba
    DevIconGemfile                         { fg="#701516", }, -- DevIconGemfile xxx ctermfg=52 guifg=#701516
    DevIconQuery                           { fg="#90a850", }, -- DevIconQuery   xxx ctermfg=107 guifg=#90a850
    DevIconVagrantfile                     { fg="#1563ff", }, -- DevIconVagrantfile xxx ctermfg=27 guifg=#1563ff
    DevIconTerraform                       { fg="#5f43e9", }, -- DevIconTerraform xxx ctermfg=93 guifg=#5f43e9
    DevIconTex                             { fg="#3d6117", }, -- DevIconTex     xxx ctermfg=22 guifg=#3d6117
    DevIconVlang                           { fg="#5d87bf", }, -- DevIconVlang   xxx ctermfg=67 guifg=#5d87bf
    DevIconApp                             { fg="#9f0500", }, -- DevIconApp     xxx ctermfg=124 guifg=#9f0500
    DevIconDropbox                         { fg="#0061fe", }, -- DevIconDropbox xxx ctermfg=27 guifg=#0061fe
    DevIconFlac                            { fg="#66d8ef", }, -- DevIconFlac    xxx ctermfg=45 guifg=#66d8ef
    DevIconBashProfile                     { fg="#89e051", }, -- DevIconBashProfile xxx ctermfg=113 guifg=#89e051
    DevIconGif                             { fg="#a074c4", }, -- DevIconGif     xxx ctermfg=140 guifg=#a074c4
    DevIconGodotProject                    { fg="#6d8086", }, -- DevIconGodotProject xxx ctermfg=66 guifg=#6d8086
    DevIconGruntfile                       { fg="#e37933", }, -- DevIconGruntfile xxx ctermfg=166 guifg=#e37933
    DevIconYaml                            { fg="#6d8086", }, -- DevIconYaml    xxx ctermfg=66 guifg=#6d8086
    DevIconVoid                            { fg="#295340", }, -- DevIconVoid    xxx ctermfg=23 guifg=#295340
    DevIconJpeg                            { fg="#a074c4", }, -- DevIconJpeg    xxx ctermfg=140 guifg=#a074c4
    DevIconJpg                             { fg="#a074c4", }, -- DevIconJpg     xxx ctermfg=140 guifg=#a074c4
    DevIconLicense                         { fg="#d0bf41", }, -- DevIconLicense xxx ctermfg=185 guifg=#d0bf41
    DevIconRmd                             { fg="#519aba", }, -- DevIconRmd     xxx ctermfg=74 guifg=#519aba
    DevIconMaterial                        { fg="#b83998", }, -- DevIconMaterial xxx ctermfg=163 guifg=#b83998
    DevIconM4A                             { fg="#66d8ef", }, -- DevIconM4A     xxx ctermfg=45 guifg=#66d8ef
    DevIconM4V                             { fg="#fd971f", }, -- DevIconM4V     xxx ctermfg=208 guifg=#fd971f
    DevIconMkv                             { fg="#fd971f", }, -- DevIconMkv     xxx ctermfg=208 guifg=#fd971f
    DevIconCts                             { fg="#519aba", }, -- DevIconCts     xxx ctermfg=74 guifg=#519aba
    DevIconNswag                           { fg="#85ea2d", }, -- DevIconNswag   xxx ctermfg=112 guifg=#85ea2d
    DevIconMarkdown                        { fg="#519aba", }, -- DevIconMarkdown xxx ctermfg=74 guifg=#519aba
    DevIconKsh                             { fg="#4d5a5e", }, -- DevIconKsh     xxx ctermfg=240 guifg=#4d5a5e
    DevIconNixOS                           { fg="#7ab1db", }, -- DevIconNixOS   xxx ctermfg=110 guifg=#7ab1db
    DevIconPhp                             { fg="#a074c4", }, -- DevIconPhp     xxx ctermfg=140 guifg=#a074c4
    DevIconOpenBSD                         { fg="#000000", }, -- DevIconOpenBSD xxx ctermfg=16 guifg=#000000
    DevIconGitCommit                       { fg="#41535b", }, -- DevIconGitCommit xxx ctermfg=239 guifg=#41535b
    DevIconIllumos                         { fg="#ff430f", }, -- DevIconIllumos xxx ctermfg=196 guifg=#ff430f
    DevIconJpegXl                          { fg="#a074c4", }, -- DevIconJpegXl  xxx ctermfg=140 guifg=#a074c4
    DevIconPyd                             { fg="#ffe291", }, -- DevIconPyd     xxx ctermfg=222 guifg=#ffe291
    DevIconMint                            { fg="#87c095", }, -- DevIconMint    xxx ctermfg=108 guifg=#87c095
    DevIconopenSUSE                        { fg="#6fb424", }, -- DevIconopenSUSE xxx ctermfg=70 guifg=#6fb424
    DevIconDiff                            { fg="#41535b", }, -- DevIconDiff    xxx ctermfg=239 guifg=#41535b
    DevIconZsh                             { fg="#89e051", }, -- DevIconZsh     xxx ctermfg=113 guifg=#89e051
    DevIconReScriptInterface               { fg="#f55385", }, -- DevIconReScriptInterface xxx ctermfg=204 guifg=#f55385
    DevIconC                               { fg="#599eff", }, -- DevIconC       xxx ctermfg=111 guifg=#599eff
    DevIconGuix                            { fg="#ffcc00", }, -- DevIconGuix    xxx ctermfg=220 guifg=#ffcc00
    DevIconBashrc                          { fg="#89e051", }, -- DevIconBashrc  xxx ctermfg=113 guifg=#89e051
    DevIconDb                              { fg="#dad8d8", }, -- DevIconDb      xxx ctermfg=188 guifg=#dad8d8
    DevIconEnv                             { fg="#faf743", }, -- DevIconEnv     xxx ctermfg=227 guifg=#faf743
    DevIconWebpack                         { fg="#519aba", }, -- DevIconWebpack xxx ctermfg=74 guifg=#519aba
    DevIconXcPlayground                    { fg="#e37933", }, -- DevIconXcPlayground xxx ctermfg=166 guifg=#e37933
    DevIconTor                             { fg="#519aba", }, -- DevIconTor     xxx ctermfg=74 guifg=#519aba
    DevIconXls                             { fg="#207245", }, -- DevIconXls     xxx ctermfg=29 guifg=#207245
    DevIconSln                             { fg="#854cc7", }, -- DevIconSln     xxx ctermfg=98 guifg=#854cc7
    DevIconWasm                            { fg="#5c4cdb", }, -- DevIconWasm    xxx ctermfg=62 guifg=#5c4cdb
    DevIconHh                              { fg="#a074c4", }, -- DevIconHh      xxx ctermfg=140 guifg=#a074c4
    DevIconSuo                             { fg="#e37933", }, -- DevIconSuo     xxx ctermfg=166 guifg=#e37933
    DevIconVala                            { fg="#7239b3", }, -- DevIconVala    xxx ctermfg=91 guifg=#7239b3
    DevIconSlim                            { fg="#e34c26", }, -- DevIconSlim    xxx ctermfg=196 guifg=#e34c26
    DevIconCPlusPlus                       { fg="#f34b7d", }, -- DevIconCPlusPlus xxx ctermfg=204 guifg=#f34b7d
    DevIconBinaryGLTF                      { fg="#ffb13b", }, -- DevIconBinaryGLTF xxx ctermfg=214 guifg=#ffb13b
    DevIconBmp                             { fg="#a074c4", }, -- DevIconBmp     xxx ctermfg=140 guifg=#a074c4
    DevIconZig                             { fg="#f69a1b", }, -- DevIconZig     xxx ctermfg=172 guifg=#f69a1b
    DevIconFish                            { fg="#4d5a5e", }, -- DevIconFish    xxx ctermfg=240 guifg=#4d5a5e
    DevIconHpp                             { fg="#a074c4", }, -- DevIconHpp     xxx ctermfg=140 guifg=#a074c4
    DevIconPackageLockJson                 { fg="#7a0d21", }, -- DevIconPackageLockJson xxx ctermfg=52 guifg=#7a0d21
    DevIconHurl                            { fg="#ff0288", }, -- DevIconHurl    xxx ctermfg=198 guifg=#ff0288
    DevIconTwig                            { fg="#8dc149", }, -- DevIconTwig    xxx ctermfg=113 guifg=#8dc149
    sym"DevIconPy.typed"                   { fg="#ffbc03", }, -- DevIconPy.typed xxx ctermfg=214 guifg=#ffbc03
    DevIconOgg                             { fg="#66d8ef", }, -- DevIconOgg     xxx ctermfg=45 guifg=#66d8ef
    DevIconConfigRu                        { fg="#701516", }, -- DevIconConfigRu xxx ctermfg=52 guifg=#701516
    DevIconCrystal                         { fg="#c8c8c8", }, -- DevIconCrystal xxx ctermfg=251 guifg=#c8c8c8
    DevIconMts                             { fg="#519aba", }, -- DevIconMts     xxx ctermfg=74 guifg=#519aba
    DevIconCs                              { fg="#596706", }, -- DevIconCs      xxx ctermfg=58 guifg=#596706
    DevIconJson5                           { fg="#cbcb41", }, -- DevIconJson5   xxx ctermfg=185 guifg=#cbcb41
    DevIconLeex                            { fg="#a074c4", }, -- DevIconLeex    xxx ctermfg=140 guifg=#a074c4
    DevIconSml                             { fg="#e37933", }, -- DevIconSml     xxx ctermfg=166 guifg=#e37933
    DevIconCss                             { fg="#42a5f5", }, -- DevIconCss     xxx ctermfg=75 guifg=#42a5f5
    DevIconCsv                             { fg="#89e051", }, -- DevIconCsv     xxx ctermfg=113 guifg=#89e051
    DevIconIco                             { fg="#cbcb41", }, -- DevIconIco     xxx ctermfg=185 guifg=#cbcb41
    DevIconAOSC                            { fg="#000000", }, -- DevIconAOSC    xxx ctermfg=16 guifg=#000000
    DevIconVimrc                           { fg="#019833", }, -- DevIconVimrc   xxx ctermfg=28 guifg=#019833
    DevIconClojureDart                     { fg="#519aba", }, -- DevIconClojureDart xxx ctermfg=74 guifg=#519aba
    DevIconRockyLinux                      { fg="#0fb37d", }, -- DevIconRockyLinux xxx ctermfg=36 guifg=#0fb37d
    DevIconBudgie                          { fg="#ffffff", }, -- DevIconBudgie  xxx ctermfg=231 guifg=#ffffff
    DevIconMdx                             { fg="#519aba", }, -- DevIconMdx     xxx ctermfg=74 guifg=#519aba
    DevIconLua                             { fg="#51a0cf", }, -- DevIconLua     xxx ctermfg=74 guifg=#51a0cf
    DevIconHxx                             { fg="#a074c4", }, -- DevIconHxx     xxx ctermfg=140 guifg=#a074c4
    DevIconSass                            { fg="#f55385", }, -- DevIconSass    xxx ctermfg=204 guifg=#f55385
    DevIconFortran                         { fg="#734f96", }, -- DevIconFortran xxx ctermfg=97 guifg=#734f96
    DevIconMOV                             { fg="#fd971f", }, -- DevIconMOV     xxx ctermfg=208 guifg=#fd971f
    DevIconSig                             { fg="#e37933", }, -- DevIconSig     xxx ctermfg=166 guifg=#e37933
    DevIconDoc                             { fg="#185abd", }, -- DevIconDoc     xxx ctermfg=26 guifg=#185abd
    DevIconProcfile                        { fg="#a074c4", }, -- DevIconProcfile xxx ctermfg=140 guifg=#a074c4
    DevIconPsb                             { fg="#519aba", }, -- DevIconPsb     xxx ctermfg=74 guifg=#519aba
    DevIconPyc                             { fg="#ffe291", }, -- DevIconPyc     xxx ctermfg=222 guifg=#ffe291
    DevIconPyo                             { fg="#ffe291", }, -- DevIconPyo     xxx ctermfg=222 guifg=#ffe291
    DevIconTsx                             { fg="#1354bf", }, -- DevIconTsx     xxx ctermfg=26 guifg=#1354bf
    DevIconRproj                           { fg="#358a5b", }, -- DevIconRproj   xxx ctermfg=29 guifg=#358a5b
    DevIconSql                             { fg="#dad8d8", }, -- DevIconSql     xxx ctermfg=188 guifg=#dad8d8
    DevIconWav                             { fg="#66d8ef", }, -- DevIconWav     xxx ctermfg=45 guifg=#66d8ef
    DevIconPl                              { fg="#519aba", }, -- DevIconPl      xxx ctermfg=74 guifg=#519aba
    DevIconGitLogo                         { fg="#f14c28", }, -- DevIconGitLogo xxx ctermfg=196 guifg=#f14c28
    DevIconPop_OS                          { fg="#48b9c7", }, -- DevIconPop_OS  xxx ctermfg=73 guifg=#48b9c7
    DevIconGentoo                          { fg="#b1abce", }, -- DevIconGentoo  xxx ctermfg=146 guifg=#b1abce
    DevIconRlib                            { fg="#dea584", }, -- DevIconRlib    xxx ctermfg=216 guifg=#dea584
    DevIconAlpine                          { fg="#0d597f", }, -- DevIconAlpine  xxx ctermfg=24 guifg=#0d597f
    DevIconTextResource                    { fg="#cbcb41", }, -- DevIconTextResource xxx ctermfg=185 guifg=#cbcb41
    DevIconEex                             { fg="#a074c4", }, -- DevIconEex     xxx ctermfg=140 guifg=#a074c4
    DevIconElf                             { fg="#9f0500", }, -- DevIconElf     xxx ctermfg=124 guifg=#9f0500
    DevIconExs                             { fg="#a074c4", }, -- DevIconExs     xxx ctermfg=140 guifg=#a074c4
    DevIconMd                              { fg="#ffffff", }, -- DevIconMd      xxx ctermfg=231 guifg=#ffffff
    DevIconSolidity                        { fg="#519aba", }, -- DevIconSolidity xxx ctermfg=74 guifg=#519aba
    DevIconAvif                            { fg="#a074c4", }, -- DevIconAvif    xxx ctermfg=140 guifg=#a074c4
    DevIconOPUS                            { fg="#f88a02", }, -- DevIconOPUS    xxx ctermfg=208 guifg=#f88a02
    DevIconWindows                         { fg="#00a4ef", }, -- DevIconWindows xxx ctermfg=39 guifg=#00a4ef
    DevIconFs                              { fg="#519aba", }, -- DevIconFs      xxx ctermfg=74 guifg=#519aba
    DevIconFsscript                        { fg="#519aba", }, -- DevIconFsscript xxx ctermfg=74 guifg=#519aba
    DevIconMustache                        { fg="#e37933", }, -- DevIconMustache xxx ctermfg=166 guifg=#e37933
    DevIconNodeModules                     { fg="#e8274b", }, -- DevIconNodeModules xxx ctermfg=197 guifg=#e8274b
    DevIconLhs                             { fg="#a074c4", }, -- DevIconLhs     xxx ctermfg=140 guifg=#a074c4
    DevIconGitConfig                       { fg="#41535b", }, -- DevIconGitConfig xxx ctermfg=239 guifg=#41535b
    DevIconGitModules                      { fg="#41535b", }, -- DevIconGitModules xxx ctermfg=239 guifg=#41535b
    DevIconGitAttributes                   { fg="#41535b", }, -- DevIconGitAttributes xxx ctermfg=239 guifg=#41535b
    DevIconGitIgnore                       { fg="#41535b", }, -- DevIconGitIgnore xxx ctermfg=239 guifg=#41535b
    DevIconDocx                            { fg="#185abd", }, -- DevIconDocx    xxx ctermfg=26 guifg=#185abd
    DevIconEjs                             { fg="#cbcb41", }, -- DevIconEjs     xxx ctermfg=185 guifg=#cbcb41
    DevIconXlsx                            { fg="#207245", }, -- DevIconXlsx    xxx ctermfg=29 guifg=#207245
    DevIconAzureCli                        { fg="#0078d4", }, -- DevIconAzureCli xxx ctermfg=32 guifg=#0078d4
    DevIconKali                            { fg="#ffffff", }, -- DevIconKali    xxx ctermfg=231 guifg=#ffffff
    DevIconStyl                            { fg="#8dc149", }, -- DevIconStyl    xxx ctermfg=113 guifg=#8dc149
    DevIconXaml                            { fg="#512bd4", }, -- DevIconXaml    xxx ctermfg=56 guifg=#512bd4
    DevIconGulpfile                        { fg="#cc3e44", }, -- DevIconGulpfile xxx ctermfg=167 guifg=#cc3e44
  }
end)
return theme
